#ifdef _WIN32
/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains magic required by Win32 DLLs to initialize
 * tag_typedef_t variables.
 * 
 * Do not, repeat, do not edit this file. Edit 'nea_tag.c' instead.
 * 
 */

#define EXPORT __declspec(dllexport)

/*
 * This file is part of the Sofia-SIP package
 *
 * Copyright (C) 2005 Nokia Corporation.
 *
 * Contact: Pekka Pessi <pekka.pessi@nokia.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */

/**@CFILE nea_tag.c
 * @brief Tags for Nokia SIP Transaction API
 *
 * @author Pekka Pessi <Pekka.Pessi@nokia.com>
 * @author Martti Mela <Martti Mela@nokia.com>
 *
 * @date Created: Tue Jul 24 22:28:34 2001 ppessi
 */

#include "config.h"

#include <string.h>
#include <assert.h>

#undef TAG_NAMESPACE
#define TAG_NAMESPACE "nea"

#define TAG_NAMESPACE "nea"

#include "sofia-sip/nea.h"
#include <sofia-sip/su_tag_class.h>
#include <sofia-sip/sip_tag_class.h>
#include <sofia-sip/url_tag_class.h>

tag_typedef_t neatag_any;
EXPORT tag_typedef_t neatag_min_expires_ref;
tag_typedef_t neatag_min_expires;
EXPORT tag_typedef_t neatag_expires_ref;
tag_typedef_t neatag_expires;
EXPORT tag_typedef_t neatag_max_expires_ref;
tag_typedef_t neatag_max_expires;
EXPORT tag_typedef_t neatag_throttle_ref;
tag_typedef_t neatag_throttle;
EXPORT tag_typedef_t neatag_minthrottle_ref;
tag_typedef_t neatag_minthrottle;
EXPORT tag_typedef_t neatag_dialog_ref;
tag_typedef_t neatag_dialog;
EXPORT tag_typedef_t neatag_eventlist_ref;
tag_typedef_t neatag_eventlist;
EXPORT tag_typedef_t neatag_fake_ref;
tag_typedef_t neatag_fake;
EXPORT tag_typedef_t neatag_reason_ref;
tag_typedef_t neatag_reason;
EXPORT tag_typedef_t neatag_retry_after_ref;
tag_typedef_t neatag_retry_after;
EXPORT tag_typedef_t neatag_exstate_ref;
tag_typedef_t neatag_exstate;
EXPORT tag_typedef_t neatag_version_ref;
tag_typedef_t neatag_version;
EXPORT tag_typedef_t neatag_view_ref;
tag_typedef_t neatag_view;
EXPORT tag_typedef_t neatag_evmagic_ref;
tag_typedef_t neatag_evmagic;
EXPORT tag_typedef_t neatag_reliable_ref;
tag_typedef_t neatag_reliable;
EXPORT tag_typedef_t neatag_sub_ref;
tag_typedef_t neatag_sub;

EXPORT tag_typedef_t neatag_strict_3265_ref;
tag_typedef_t neatag_strict_3265;

#include <windows.h>

BOOL WINAPI DllMain(HINSTANCE hInst, DWORD fwdReason, LPVOID fImpLoad)
{
  tag_typedef_t _neatag_throttle = UINTTAG_TYPEDEF(throttle);
  tag_typedef_t _neatag_throttle_ref =
    REFTAG_TYPEDEF(neatag_throttle);
  tag_typedef_t _neatag_fake = BOOLTAG_TYPEDEF(fake);
  tag_typedef_t _neatag_fake_ref =
    REFTAG_TYPEDEF(neatag_fake);
  tag_typedef_t _neatag_reliable = BOOLTAG_TYPEDEF(reliable);
  tag_typedef_t _neatag_reliable_ref =
    REFTAG_TYPEDEF(neatag_reliable);
  tag_typedef_t _neatag_retry_after = UINTTAG_TYPEDEF(retry_after);
  tag_typedef_t _neatag_retry_after_ref =
    REFTAG_TYPEDEF(neatag_retry_after);
  tag_typedef_t _neatag_reason = STRTAG_TYPEDEF(reason);
  tag_typedef_t _neatag_reason_ref =
    REFTAG_TYPEDEF(neatag_reason);
  tag_typedef_t _neatag_strict_3265 = BOOLTAG_TYPEDEF(strict_3265);
  tag_typedef_t _neatag_strict_3265_ref =
    REFTAG_TYPEDEF(neatag_strict_3265);
  tag_typedef_t _neatag_sub = PTRTAG_TYPEDEF(sub);
  tag_typedef_t _neatag_sub_ref =
    REFTAG_TYPEDEF(neatag_sub);
  tag_typedef_t _neatag_version = INTTAG_TYPEDEF(version);
  tag_typedef_t _neatag_version_ref =
    REFTAG_TYPEDEF(neatag_version);
  tag_typedef_t _neatag_any = NSTAG_TYPEDEF(*);
  tag_typedef_t _neatag_any_ref =
    REFTAG_TYPEDEF(neatag_any);
  tag_typedef_t _neatag_eventlist = BOOLTAG_TYPEDEF(eventlist);
  tag_typedef_t _neatag_eventlist_ref =
    REFTAG_TYPEDEF(neatag_eventlist);
  tag_typedef_t _neatag_view = PTRTAG_TYPEDEF(view);
  tag_typedef_t _neatag_view_ref =
    REFTAG_TYPEDEF(neatag_view);
  tag_typedef_t _neatag_evmagic = PTRTAG_TYPEDEF(evmagic);
  tag_typedef_t _neatag_evmagic_ref =
    REFTAG_TYPEDEF(neatag_evmagic);
  tag_typedef_t _neatag_max_expires = UINTTAG_TYPEDEF(max_expires);
  tag_typedef_t _neatag_max_expires_ref =
    REFTAG_TYPEDEF(neatag_max_expires);
  tag_typedef_t _neatag_min_expires = UINTTAG_TYPEDEF(min_expires);
  tag_typedef_t _neatag_min_expires_ref =
    REFTAG_TYPEDEF(neatag_min_expires);
  tag_typedef_t _neatag_exstate = STRTAG_TYPEDEF(exstate);
  tag_typedef_t _neatag_exstate_ref =
    REFTAG_TYPEDEF(neatag_exstate);
  tag_typedef_t _neatag_expires = UINTTAG_TYPEDEF(expires);
  tag_typedef_t _neatag_expires_ref =
    REFTAG_TYPEDEF(neatag_expires);
  tag_typedef_t _neatag_dialog = PTRTAG_TYPEDEF(dialog);
  tag_typedef_t _neatag_dialog_ref =
    REFTAG_TYPEDEF(neatag_dialog);
  tag_typedef_t _neatag_minthrottle = UINTTAG_TYPEDEF(minthrottle);
  tag_typedef_t _neatag_minthrottle_ref =
    REFTAG_TYPEDEF(neatag_minthrottle);

  *(struct tag_type_s *)neatag_throttle = *_neatag_throttle;
  *(struct tag_type_s *)neatag_throttle_ref = *_neatag_throttle_ref;
  *(struct tag_type_s *)neatag_fake = *_neatag_fake;
  *(struct tag_type_s *)neatag_fake_ref = *_neatag_fake_ref;
  *(struct tag_type_s *)neatag_retry_after = *_neatag_retry_after;
  *(struct tag_type_s *)neatag_retry_after_ref = *_neatag_retry_after_ref;
  *(struct tag_type_s *)neatag_reliable = *_neatag_reliable;
  *(struct tag_type_s *)neatag_reliable_ref = *_neatag_reliable_ref;
  *(struct tag_type_s *)neatag_reason = *_neatag_reason;
  *(struct tag_type_s *)neatag_reason_ref = *_neatag_reason_ref;
  *(struct tag_type_s *)neatag_strict_3265 = *_neatag_strict_3265;
  *(struct tag_type_s *)neatag_strict_3265_ref = *_neatag_strict_3265_ref;
  *(struct tag_type_s *)neatag_sub = *_neatag_sub;
  *(struct tag_type_s *)neatag_sub_ref = *_neatag_sub_ref;
  *(struct tag_type_s *)neatag_version = *_neatag_version;
  *(struct tag_type_s *)neatag_version_ref = *_neatag_version_ref;
  *(struct tag_type_s *)neatag_any = *_neatag_any;
  *(struct tag_type_s *)neatag_any_ref = *_neatag_any_ref;
  *(struct tag_type_s *)neatag_eventlist = *_neatag_eventlist;
  *(struct tag_type_s *)neatag_eventlist_ref = *_neatag_eventlist_ref;
  *(struct tag_type_s *)neatag_view = *_neatag_view;
  *(struct tag_type_s *)neatag_view_ref = *_neatag_view_ref;
  *(struct tag_type_s *)neatag_min_expires = *_neatag_min_expires;
  *(struct tag_type_s *)neatag_min_expires_ref = *_neatag_min_expires_ref;
  *(struct tag_type_s *)neatag_max_expires = *_neatag_max_expires;
  *(struct tag_type_s *)neatag_max_expires_ref = *_neatag_max_expires_ref;
  *(struct tag_type_s *)neatag_evmagic = *_neatag_evmagic;
  *(struct tag_type_s *)neatag_evmagic_ref = *_neatag_evmagic_ref;
  *(struct tag_type_s *)neatag_expires = *_neatag_expires;
  *(struct tag_type_s *)neatag_expires_ref = *_neatag_expires_ref;
  *(struct tag_type_s *)neatag_exstate = *_neatag_exstate;
  *(struct tag_type_s *)neatag_exstate_ref = *_neatag_exstate_ref;
  *(struct tag_type_s *)neatag_dialog = *_neatag_dialog;
  *(struct tag_type_s *)neatag_dialog_ref = *_neatag_dialog_ref;
  *(struct tag_type_s *)neatag_minthrottle = *_neatag_minthrottle;
  *(struct tag_type_s *)neatag_minthrottle_ref = *_neatag_minthrottle_ref;

  return TRUE;
}

#endif
