#ifdef _WIN32
/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains magic required by Win32 DLLs to initialize
 * tag_typedef_t variables.
 * 
 * Do not, repeat, do not edit this file. Edit 'nth_tag.c' instead.
 * 
 */

#define EXPORT __declspec(dllexport)

/*
 * This file is part of the Sofia-SIP package
 *
 * Copyright (C) 2005 Nokia Corporation.
 *
 * Contact: Pekka Pessi <pekka.pessi@nokia.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */

/**@CFILE nth_tag.c
 * @brief Tags for HTTP Transaction API
 *
 * @note This file is used to automatically generate
 * nth_tag_ref.c and nth_tag_dll.c
 *
 * @author Pekka Pessi <Pekka.Pessi@nokia.com>
 *
 * @date Created: Tue Jul 24 22:28:34 2001 ppessi
 */

#include "config.h"

#include <string.h>
#include <assert.h>

#undef TAG_NAMESPACE
#define TAG_NAMESPACE "nth"

#define TAG_NAMESPACE "nth"

#include "sofia-sip/nth_tag.h"
#include <sofia-sip/su_tag_class.h>
#include <sofia-sip/http_tag_class.h>
#include <sofia-sip/url_tag_class.h>

#include <sofia-sip/http_protos.h>

tag_typedef_t nthtag_any;

/* Common */
EXPORT tag_typedef_t nthtag_mclass_ref;
tag_typedef_t nthtag_mclass;
EXPORT tag_typedef_t nthtag_message_ref;
tag_typedef_t nthtag_message;
EXPORT tag_typedef_t nthtag_mflags_ref;
tag_typedef_t nthtag_mflags;
EXPORT tag_typedef_t nthtag_streaming_ref;
tag_typedef_t nthtag_streaming;

/* Client */
EXPORT tag_typedef_t nthtag_proxy_ref;
tag_typedef_t nthtag_proxy;
EXPORT tag_typedef_t nthtag_expires_ref;
tag_typedef_t nthtag_expires;
EXPORT tag_typedef_t nthtag_error_msg_ref;
tag_typedef_t nthtag_error_msg;
EXPORT tag_typedef_t nthtag_template_ref;
tag_typedef_t nthtag_template;
EXPORT tag_typedef_t nthtag_authentication_ref;
tag_typedef_t nthtag_authentication;

/* Server */
EXPORT tag_typedef_t nthtag_root_ref;
tag_typedef_t nthtag_root;
EXPORT tag_typedef_t nthtag_strict_host_ref;
tag_typedef_t nthtag_strict_host;

/**@def NTHTAG_AUTH_MODULE()
 *
 * Pointer to authentication module.
 *
 * A site requires authentication from the clients if passed an
 * authentication module pointer with NTHTAG_AUTH_MODULE(). Incoming client
 * request is challenged with 401, upon successful authentication the
 * authenticated username is stored in the #auth_status_t structure
 * associated with the #nth_request_t object. It is up to application to
 * authorize the user.
 *
 * @sa nth_site_create(), nth_site_set_params(), nth_request_auth().
 */
EXPORT tag_typedef_t nthtag_auth_module_ref;
tag_typedef_t nthtag_auth_module;

#include <windows.h>

BOOL WINAPI DllMain(HINSTANCE hInst, DWORD fwdReason, LPVOID fImpLoad)
{
  tag_typedef_t _nthtag_mclass = PTRTAG_TYPEDEF(mclass);
  tag_typedef_t _nthtag_mclass_ref =
    REFTAG_TYPEDEF(nthtag_mclass);
  tag_typedef_t _nthtag_any = NSTAG_TYPEDEF(*);
  tag_typedef_t _nthtag_any_ref =
    REFTAG_TYPEDEF(nthtag_any);
  tag_typedef_t _nthtag_streaming = BOOLTAG_TYPEDEF(streaming);
  tag_typedef_t _nthtag_streaming_ref =
    REFTAG_TYPEDEF(nthtag_streaming);
  tag_typedef_t _nthtag_strict_host = BOOLTAG_TYPEDEF(scrict_host);
  tag_typedef_t _nthtag_strict_host_ref =
    REFTAG_TYPEDEF(nthtag_strict_host);
  tag_typedef_t _nthtag_mflags = INTTAG_TYPEDEF(mflags);
  tag_typedef_t _nthtag_mflags_ref =
    REFTAG_TYPEDEF(nthtag_mflags);
  tag_typedef_t _nthtag_auth_module = PTRTAG_TYPEDEF(auth_module);
  tag_typedef_t _nthtag_auth_module_ref =
    REFTAG_TYPEDEF(nthtag_auth_module);
  tag_typedef_t _nthtag_expires = UINTTAG_TYPEDEF(expires);
  tag_typedef_t _nthtag_expires_ref =
    REFTAG_TYPEDEF(nthtag_expires);
  tag_typedef_t _nthtag_template = PTRTAG_TYPEDEF(template);
  tag_typedef_t _nthtag_template_ref =
    REFTAG_TYPEDEF(nthtag_template);
  tag_typedef_t _nthtag_message = PTRTAG_TYPEDEF(message);
  tag_typedef_t _nthtag_message_ref =
    REFTAG_TYPEDEF(nthtag_message);
  tag_typedef_t _nthtag_root = PTRTAG_TYPEDEF(root);
  tag_typedef_t _nthtag_root_ref =
    REFTAG_TYPEDEF(nthtag_root);
  tag_typedef_t _nthtag_proxy = URLTAG_TYPEDEF(proxy);
  tag_typedef_t _nthtag_proxy_ref =
    REFTAG_TYPEDEF(nthtag_proxy);
  tag_typedef_t _nthtag_authentication = PTRTAG_TYPEDEF(authentication);
  tag_typedef_t _nthtag_authentication_ref =
    REFTAG_TYPEDEF(nthtag_authentication);
  tag_typedef_t _nthtag_error_msg = BOOLTAG_TYPEDEF(error_msg);
  tag_typedef_t _nthtag_error_msg_ref =
    REFTAG_TYPEDEF(nthtag_error_msg);

  *(struct tag_type_s *)nthtag_mclass = *_nthtag_mclass;
  *(struct tag_type_s *)nthtag_mclass_ref = *_nthtag_mclass_ref;
  *(struct tag_type_s *)nthtag_any = *_nthtag_any;
  *(struct tag_type_s *)nthtag_any_ref = *_nthtag_any_ref;
  *(struct tag_type_s *)nthtag_streaming = *_nthtag_streaming;
  *(struct tag_type_s *)nthtag_streaming_ref = *_nthtag_streaming_ref;
  *(struct tag_type_s *)nthtag_strict_host = *_nthtag_strict_host;
  *(struct tag_type_s *)nthtag_strict_host_ref = *_nthtag_strict_host_ref;
  *(struct tag_type_s *)nthtag_mflags = *_nthtag_mflags;
  *(struct tag_type_s *)nthtag_mflags_ref = *_nthtag_mflags_ref;
  *(struct tag_type_s *)nthtag_auth_module = *_nthtag_auth_module;
  *(struct tag_type_s *)nthtag_auth_module_ref = *_nthtag_auth_module_ref;
  *(struct tag_type_s *)nthtag_expires = *_nthtag_expires;
  *(struct tag_type_s *)nthtag_expires_ref = *_nthtag_expires_ref;
  *(struct tag_type_s *)nthtag_template = *_nthtag_template;
  *(struct tag_type_s *)nthtag_template_ref = *_nthtag_template_ref;
  *(struct tag_type_s *)nthtag_message = *_nthtag_message;
  *(struct tag_type_s *)nthtag_message_ref = *_nthtag_message_ref;
  *(struct tag_type_s *)nthtag_root = *_nthtag_root;
  *(struct tag_type_s *)nthtag_root_ref = *_nthtag_root_ref;
  *(struct tag_type_s *)nthtag_proxy = *_nthtag_proxy;
  *(struct tag_type_s *)nthtag_proxy_ref = *_nthtag_proxy_ref;
  *(struct tag_type_s *)nthtag_authentication = *_nthtag_authentication;
  *(struct tag_type_s *)nthtag_authentication_ref = *_nthtag_authentication_ref;
  *(struct tag_type_s *)nthtag_error_msg = *_nthtag_error_msg;
  *(struct tag_type_s *)nthtag_error_msg_ref = *_nthtag_error_msg_ref;

  return TRUE;
}

#endif
