#ifdef _WIN32
/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains magic required by Win32 DLLs to initialize
 * tag_typedef_t variables.
 * 
 * Do not, repeat, do not edit this file. Edit 'stun_tag.c' instead.
 * 
 */

#define EXPORT __declspec(dllexport)

/*
 * This file is part of the Sofia-SIP package
 *
 * Copyright (C) 2005-2006 Nokia Corporation.
 *
 * Contact: Pekka Pessi <pekka.pessi@nokia.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */

/**@internal @CFILE stun_tag.c  Tags and tag lists for Offer/Answer Engine
 *
 * @author Pekka Pessi <Pekka.Pessi@nokia.com>
 * @author Martti Mela <Martti.Mela@nokia.com>
 * @author Kai Vehmanen <Kai.Vehmanen@nokia.com>
 *
 * @date Created: Wed Aug  3 20:28:17 EEST 2005
 */

#include "config.h"

#undef TAG_NAMESPACE
#define TAG_NAMESPACE "stun"

#define TAG_NAMESPACE "stun"

#include <sofia-sip/su_tag_class.h>
#include <sofia-sip/stun_tag.h>

/**@def STUNTAG_ANY()
 *
 * Filter tag matching any STUNTAG_*().
 */
tag_typedef_t stuntag_any;

/**@def STUNTAG_DOMAIN(x)
 *
 * The domain to use in DNS-SRV based STUN server discovery.
 * Note: this is commonly the domain part of a public SIP
 * address (AOR). See sect 9.1 of RFC3489.
 *
 * @par Used with
 *    nua_set_params() \n
 *    nua_get_params() \n
 *    nua_invite() \n
 *    nua_respond()
 *
 * @par Parameter type
 *    char const *

 */
EXPORT tag_typedef_t stuntag_domain_ref;
tag_typedef_t stuntag_domain;

/**@def STUNTAG_SERVER(x)
 *
 * Fully qualified host name, or dotted IP address of the STUN server
 * address. If defined, the DNS-SRV based discovery (@see STUNTAG_DOMAIN())
 * will be skipped.
 *
 * @par Used with
 *    nua_set_params() \n
 *    nua_get_params() \n
 *    nua_invite() \n
 *    nua_respond()
 *
 * @par Parameter type
 *    char const *
 *
 * @par Values
 *    NULL terminated character string containing a domain name,
 *    IPv4 address, or IPv6 address.
 *
 * Corresponding tag taking reference parameter is STUNTAG_SERVER_REF()
*/
EXPORT tag_typedef_t stuntag_server_ref;
tag_typedef_t stuntag_server;

/**@def STUNTAG_REQUIRE_INTEGRITY(x)
 *
 * Whether to require support for shared-secret based packet
 * authentication and integrity checks (see sect 9.2 of RFC3489).
 * If false, integrity checks are performed only when server supports it.
 *
 * @par Used with
 *    nua_create() \n
 *
 * @par Parameter type
 *    int (boolean)
 *
 * @par Values
 *    @c !=0 enable
 *    @c 0 disable
 *
 * Corresponding tag taking reference parameter is STUNTAG_INTEGRITY_REF()
 */
EXPORT tag_typedef_t stuntag_require_integrity_ref;
tag_typedef_t stuntag_require_integrity;

/**@def STUNTAG_INTEGRITY(x)
 *
 * XXX: should this tag be deprecated in favor of just supporting
 * STUNTAG_REQURIE_INTEGRITY() instead...?
 */
EXPORT tag_typedef_t stuntag_integrity_ref;
tag_typedef_t stuntag_integrity;

/**@def STUNTAG_SOCKET(x)
 *
 * Bind socket for STUN.
 *
 * @par Used with
 *    stun_handle_bind() \n
 *
 * @par Parameter type
 *    int (su_socket_t)
 *
 * @par Values
 *    IPv4 (AF_INET) socket
 *
 * Corresponding tag taking reference parameter is STUNTAG_SOCKET_REF()
 */
EXPORT tag_typedef_t stuntag_socket_ref;
tag_typedef_t stuntag_socket;

/**@def STUNTAG_REGISTER_EVENTS(x)
 *
 * Register socket events for eventloop owned by STUN.
 *
 * @par Used with
 *    stun_bind() \n
 *    stun_get_lifetime() \n
 *    stun_get_nattype() \n
 *    stun_keepalive() \n
 *
 * @par Parameter type
 *    bool
 *
 * @par Values
 *    false (0) or true (nonzero)
 *
 * Corresponding tag taking reference parameter is STUNTAG_REGISTER_EVENTS_REF()
 */
EXPORT tag_typedef_t stuntag_register_events_ref;
tag_typedef_t stuntag_register_events;

/**@def STUNTAG_ACTION(x)
 *
 * Command action for STUN request.
 *
 * @par Used with
 *    stun_handle_bind() \n
 *
 * @par Parameter type
 *    int (stun_action_t)
 *
 * @par Values
 *    See types for stun_action_t in <sofia-sip/stun.h>
 *
 * Corresponding tag taking reference parameter is STUNTAG_ACTION_REF()
 */
EXPORT tag_typedef_t stuntag_action_ref;
tag_typedef_t stuntag_action;

/* ---------------------------------------------------------------------- */

/**@def STUNTAG_CHANGE_IP(x)
 *
 * Add CHANGE-REQUEST attribute with "change IP" flag to the request.
 *
 * @par Used with
 *    stun_make_binding_req() \n
 *
 * @par Parameter type
 *    bool
 *
 * Corresponding tag taking reference parameter is STUNTAG_CHANGE_IP_REF()
 */
EXPORT tag_typedef_t stuntag_change_ip_ref;
tag_typedef_t stuntag_change_ip;

/**@def STUNTAG_CHANGE_PORT(x)
 *
 * Add CHANGE-REQUEST attribute with "change port" flag to the request.
 *
 * @par Used with
 *    stun_make_binding_req() \n
 *
 * @par Parameter type
 *    bool
 *
 * Corresponding tag taking reference parameter is STUNTAG_CHANGE_PORT_REF()
 */
EXPORT tag_typedef_t stuntag_change_port_ref;
tag_typedef_t stuntag_change_port;

/* ---------------------------------------------------------------------- */

/**@def STUNTAG_TIMEOUT(x)
 *
 * Timeout controls the launching of the STUN keepalive timer.
 *
 * @par Used with
 *    stun_keepalive() \n
 *
 * @par Parameter type
 *    int
 *
 * Corresponding tag taking reference parameter is STUNTAG_TIMEOUT_REF()
 */
EXPORT tag_typedef_t stuntag_timeout_ref;
tag_typedef_t stuntag_timeout;

EXPORT tag_type_t stun_tag_list[] =
{
  stuntag_action,
  stuntag_change_port,
  stuntag_server,
  stuntag_timeout,
  stuntag_socket,
  stuntag_require_integrity,
  stuntag_integrity,
  stuntag_change_ip,
  stuntag_domain,
  stuntag_register_events,
  NULL
};

#include <windows.h>

BOOL WINAPI DllMain(HINSTANCE hInst, DWORD fwdReason, LPVOID fImpLoad)
{
  tag_typedef_t _stuntag_action = INTTAG_TYPEDEF(action);
  tag_typedef_t _stuntag_action_ref =
    REFTAG_TYPEDEF(stuntag_action);
  tag_typedef_t _stuntag_change_port = BOOLTAG_TYPEDEF(change_port);
  tag_typedef_t _stuntag_change_port_ref =
    REFTAG_TYPEDEF(stuntag_change_port);
  tag_typedef_t _stuntag_server = STRTAG_TYPEDEF(server);
  tag_typedef_t _stuntag_server_ref =
    REFTAG_TYPEDEF(stuntag_server);
  tag_typedef_t _stuntag_timeout = INTTAG_TYPEDEF(timeout);
  tag_typedef_t _stuntag_timeout_ref =
    REFTAG_TYPEDEF(stuntag_timeout);
  tag_typedef_t _stuntag_socket = SOCKETTAG_TYPEDEF(socket);
  tag_typedef_t _stuntag_socket_ref =
    REFTAG_TYPEDEF(stuntag_socket);
  tag_typedef_t _stuntag_require_integrity = BOOLTAG_TYPEDEF(require_integrity);
  tag_typedef_t _stuntag_require_integrity_ref =
    REFTAG_TYPEDEF(stuntag_require_integrity);
  tag_typedef_t _stuntag_integrity = BOOLTAG_TYPEDEF(integrity);
  tag_typedef_t _stuntag_integrity_ref =
    REFTAG_TYPEDEF(stuntag_integrity);
  tag_typedef_t _stuntag_change_ip = BOOLTAG_TYPEDEF(change_ip);
  tag_typedef_t _stuntag_change_ip_ref =
    REFTAG_TYPEDEF(stuntag_change_ip);
  tag_typedef_t _stuntag_domain = STRTAG_TYPEDEF(domain);
  tag_typedef_t _stuntag_domain_ref =
    REFTAG_TYPEDEF(stuntag_domain);
  tag_typedef_t _stuntag_any = NSTAG_TYPEDEF(*);
  tag_typedef_t _stuntag_any_ref =
    REFTAG_TYPEDEF(stuntag_any);
  tag_typedef_t _stuntag_register_events = BOOLTAG_TYPEDEF(register_events);
  tag_typedef_t _stuntag_register_events_ref =
    REFTAG_TYPEDEF(stuntag_register_events);

  *(struct tag_type_s *)stuntag_action = *_stuntag_action;
  *(struct tag_type_s *)stuntag_action_ref = *_stuntag_action_ref;
  *(struct tag_type_s *)stuntag_change_port = *_stuntag_change_port;
  *(struct tag_type_s *)stuntag_change_port_ref = *_stuntag_change_port_ref;
  *(struct tag_type_s *)stuntag_server = *_stuntag_server;
  *(struct tag_type_s *)stuntag_server_ref = *_stuntag_server_ref;
  *(struct tag_type_s *)stuntag_timeout = *_stuntag_timeout;
  *(struct tag_type_s *)stuntag_timeout_ref = *_stuntag_timeout_ref;
  *(struct tag_type_s *)stuntag_socket = *_stuntag_socket;
  *(struct tag_type_s *)stuntag_socket_ref = *_stuntag_socket_ref;
  *(struct tag_type_s *)stuntag_require_integrity = *_stuntag_require_integrity;
  *(struct tag_type_s *)stuntag_require_integrity_ref = *_stuntag_require_integrity_ref;
  *(struct tag_type_s *)stuntag_integrity = *_stuntag_integrity;
  *(struct tag_type_s *)stuntag_integrity_ref = *_stuntag_integrity_ref;
  *(struct tag_type_s *)stuntag_change_ip = *_stuntag_change_ip;
  *(struct tag_type_s *)stuntag_change_ip_ref = *_stuntag_change_ip_ref;
  *(struct tag_type_s *)stuntag_domain = *_stuntag_domain;
  *(struct tag_type_s *)stuntag_domain_ref = *_stuntag_domain_ref;
  *(struct tag_type_s *)stuntag_register_events = *_stuntag_register_events;
  *(struct tag_type_s *)stuntag_register_events_ref = *_stuntag_register_events_ref;
  *(struct tag_type_s *)stuntag_any = *_stuntag_any;
  *(struct tag_type_s *)stuntag_any_ref = *_stuntag_any_ref;

  return TRUE;
}

#endif
