#ifdef _WIN32
/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains magic required by Win32 DLLs to initialize
 * tag_typedef_t variables.
 * 
 * Do not, repeat, do not edit this file. Edit 'sip_tag.c' instead.
 * 
 */

#define EXPORT __declspec(dllexport)

/*
 * This file is part of the Sofia-SIP package
 *
 * Copyright (C) 2005 Nokia Corporation.
 *
 * Contact: Pekka Pessi <pekka.pessi@nokia.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */

/**@CFILE sip_tag.c  SIP Tags.
 *
 * This file is automatically generated from <sip.h> by msg_parser.awk.
 *
 * @author Pekka Pessi <Pekka.Pessi@nokia.com>.
 *
 * @date Created: Fri Feb 23 12:46:42 2001 ppessi
 */

#include "config.h"

#include <assert.h>
#include <stddef.h>
#include <string.h>

#include <sofia-sip/su.h>

#undef TAG_NAMESPACE
#define TAG_NAMESPACE "sip"

#define TAG_NAMESPACE "sip"

#include "sofia-sip/sip_parser.h"
#include <sofia-sip/sip_tag.h>

#include <sofia-sip/su_tag_class.h>
#include <sofia-sip/su_tag_inline.h>
#include <sofia-sip/sip_tag_class.h>

#include <sofia-sip/su_tagarg.h>

tag_typedef_t siptag_any;

EXPORT tag_typedef_t siptag_sip_ref;
tag_typedef_t siptag_sip;

EXPORT tag_typedef_t siptag_header_ref;
tag_typedef_t siptag_header;

EXPORT tag_typedef_t siptag_header_str_ref;
tag_typedef_t siptag_header_str;

EXPORT tag_typedef_t siptag_end_ref;
tag_typedef_t siptag_end;


extern msg_hclass_t sip_request_class[];

/**@ingroup sip_request
 * Tag for @ref sip_request "request line" object.
 */
EXPORT tag_typedef_t siptag_request_ref;
tag_typedef_t siptag_request;
/**@ingroup sip_request
 * Tag for string with @ref sip_request "request line" value.
 */
EXPORT tag_typedef_t siptag_request_str_ref;
tag_typedef_t siptag_request_str;

extern msg_hclass_t sip_status_class[];

/**@ingroup sip_status
 * Tag for @ref sip_status "status line" object.
 */
EXPORT tag_typedef_t siptag_status_ref;
tag_typedef_t siptag_status;
/**@ingroup sip_status
 * Tag for string with @ref sip_status "status line" value.
 */
EXPORT tag_typedef_t siptag_status_str_ref;
tag_typedef_t siptag_status_str;

extern msg_hclass_t sip_via_class[];

/**@ingroup sip_via
 * Tag for @ref sip_via "Via header" object.
 */
EXPORT tag_typedef_t siptag_via_ref;
tag_typedef_t siptag_via;
/**@ingroup sip_via
 * Tag for string with @ref sip_via "Via header" value.
 */
EXPORT tag_typedef_t siptag_via_str_ref;
tag_typedef_t siptag_via_str;

extern msg_hclass_t sip_route_class[];

/**@ingroup sip_route
 * Tag for @ref sip_route "Route header" object.
 */
EXPORT tag_typedef_t siptag_route_ref;
tag_typedef_t siptag_route;
/**@ingroup sip_route
 * Tag for string with @ref sip_route "Route header" value.
 */
EXPORT tag_typedef_t siptag_route_str_ref;
tag_typedef_t siptag_route_str;

extern msg_hclass_t sip_record_route_class[];

/**@ingroup sip_record_route
 * Tag for @ref sip_record_route "Record-Route header" object.
 */
EXPORT tag_typedef_t siptag_record_route_ref;
tag_typedef_t siptag_record_route;
/**@ingroup sip_record_route
 * Tag for string with @ref sip_record_route "Record-Route header" value.
 */
EXPORT tag_typedef_t siptag_record_route_str_ref;
tag_typedef_t siptag_record_route_str;

extern msg_hclass_t sip_max_forwards_class[];

/**@ingroup sip_max_forwards
 * Tag for @ref sip_max_forwards "Max-Forwards header" object.
 */
EXPORT tag_typedef_t siptag_max_forwards_ref;
tag_typedef_t siptag_max_forwards;
/**@ingroup sip_max_forwards
 * Tag for string with @ref sip_max_forwards "Max-Forwards header" value.
 */
EXPORT tag_typedef_t siptag_max_forwards_str_ref;
tag_typedef_t siptag_max_forwards_str;

extern msg_hclass_t sip_proxy_require_class[];

/**@ingroup sip_proxy_require
 * Tag for @ref sip_proxy_require "Proxy-Require header" object.
 */
EXPORT tag_typedef_t siptag_proxy_require_ref;
tag_typedef_t siptag_proxy_require;
/**@ingroup sip_proxy_require
 * Tag for string with @ref sip_proxy_require "Proxy-Require header" value.
 */
EXPORT tag_typedef_t siptag_proxy_require_str_ref;
tag_typedef_t siptag_proxy_require_str;

extern msg_hclass_t sip_from_class[];

/**@ingroup sip_from
 * Tag for @ref sip_from "From header" object.
 */
EXPORT tag_typedef_t siptag_from_ref;
tag_typedef_t siptag_from;
/**@ingroup sip_from
 * Tag for string with @ref sip_from "From header" value.
 */
EXPORT tag_typedef_t siptag_from_str_ref;
tag_typedef_t siptag_from_str;

extern msg_hclass_t sip_to_class[];

/**@ingroup sip_to
 * Tag for @ref sip_to "To header" object.
 */
EXPORT tag_typedef_t siptag_to_ref;
tag_typedef_t siptag_to;
/**@ingroup sip_to
 * Tag for string with @ref sip_to "To header" value.
 */
EXPORT tag_typedef_t siptag_to_str_ref;
tag_typedef_t siptag_to_str;

extern msg_hclass_t sip_call_id_class[];

/**@ingroup sip_call_id
 * Tag for @ref sip_call_id "Call-ID header" object.
 */
EXPORT tag_typedef_t siptag_call_id_ref;
tag_typedef_t siptag_call_id;
/**@ingroup sip_call_id
 * Tag for string with @ref sip_call_id "Call-ID header" value.
 */
EXPORT tag_typedef_t siptag_call_id_str_ref;
tag_typedef_t siptag_call_id_str;

extern msg_hclass_t sip_cseq_class[];

/**@ingroup sip_cseq
 * Tag for @ref sip_cseq "CSeq header" object.
 */
EXPORT tag_typedef_t siptag_cseq_ref;
tag_typedef_t siptag_cseq;
/**@ingroup sip_cseq
 * Tag for string with @ref sip_cseq "CSeq header" value.
 */
EXPORT tag_typedef_t siptag_cseq_str_ref;
tag_typedef_t siptag_cseq_str;

extern msg_hclass_t sip_contact_class[];

/**@ingroup sip_contact
 * Tag for @ref sip_contact "Contact header" object.
 */
EXPORT tag_typedef_t siptag_contact_ref;
tag_typedef_t siptag_contact;
/**@ingroup sip_contact
 * Tag for string with @ref sip_contact "Contact header" value.
 */
EXPORT tag_typedef_t siptag_contact_str_ref;
tag_typedef_t siptag_contact_str;

extern msg_hclass_t sip_rseq_class[];

/**@ingroup sip_rseq
 * Tag for @ref sip_rseq "RSeq header" object.
 */
EXPORT tag_typedef_t siptag_rseq_ref;
tag_typedef_t siptag_rseq;
/**@ingroup sip_rseq
 * Tag for string with @ref sip_rseq "RSeq header" value.
 */
EXPORT tag_typedef_t siptag_rseq_str_ref;
tag_typedef_t siptag_rseq_str;

extern msg_hclass_t sip_rack_class[];

/**@ingroup sip_rack
 * Tag for @ref sip_rack "RAck header" object.
 */
EXPORT tag_typedef_t siptag_rack_ref;
tag_typedef_t siptag_rack;
/**@ingroup sip_rack
 * Tag for string with @ref sip_rack "RAck header" value.
 */
EXPORT tag_typedef_t siptag_rack_str_ref;
tag_typedef_t siptag_rack_str;

extern msg_hclass_t sip_request_disposition_class[];

/**@ingroup sip_request_disposition
 * Tag for @ref sip_request_disposition "Request-Disposition header" object.
 */
EXPORT tag_typedef_t siptag_request_disposition_ref;
tag_typedef_t siptag_request_disposition;
/**@ingroup sip_request_disposition
 * Tag for string with @ref sip_request_disposition "Request-Disposition header" value.
 */
EXPORT tag_typedef_t siptag_request_disposition_str_ref;
tag_typedef_t siptag_request_disposition_str;

extern msg_hclass_t sip_accept_contact_class[];

/**@ingroup sip_accept_contact
 * Tag for @ref sip_accept_contact "Accept-Contact header" object.
 */
EXPORT tag_typedef_t siptag_accept_contact_ref;
tag_typedef_t siptag_accept_contact;
/**@ingroup sip_accept_contact
 * Tag for string with @ref sip_accept_contact "Accept-Contact header" value.
 */
EXPORT tag_typedef_t siptag_accept_contact_str_ref;
tag_typedef_t siptag_accept_contact_str;

extern msg_hclass_t sip_reject_contact_class[];

/**@ingroup sip_reject_contact
 * Tag for @ref sip_reject_contact "Reject-Contact header" object.
 */
EXPORT tag_typedef_t siptag_reject_contact_ref;
tag_typedef_t siptag_reject_contact;
/**@ingroup sip_reject_contact
 * Tag for string with @ref sip_reject_contact "Reject-Contact header" value.
 */
EXPORT tag_typedef_t siptag_reject_contact_str_ref;
tag_typedef_t siptag_reject_contact_str;

extern msg_hclass_t sip_expires_class[];

/**@ingroup sip_expires
 * Tag for @ref sip_expires "Expires header" object.
 */
EXPORT tag_typedef_t siptag_expires_ref;
tag_typedef_t siptag_expires;
/**@ingroup sip_expires
 * Tag for string with @ref sip_expires "Expires header" value.
 */
EXPORT tag_typedef_t siptag_expires_str_ref;
tag_typedef_t siptag_expires_str;

extern msg_hclass_t sip_date_class[];

/**@ingroup sip_date
 * Tag for @ref sip_date "Date header" object.
 */
EXPORT tag_typedef_t siptag_date_ref;
tag_typedef_t siptag_date;
/**@ingroup sip_date
 * Tag for string with @ref sip_date "Date header" value.
 */
EXPORT tag_typedef_t siptag_date_str_ref;
tag_typedef_t siptag_date_str;

extern msg_hclass_t sip_retry_after_class[];

/**@ingroup sip_retry_after
 * Tag for @ref sip_retry_after "Retry-After header" object.
 */
EXPORT tag_typedef_t siptag_retry_after_ref;
tag_typedef_t siptag_retry_after;
/**@ingroup sip_retry_after
 * Tag for string with @ref sip_retry_after "Retry-After header" value.
 */
EXPORT tag_typedef_t siptag_retry_after_str_ref;
tag_typedef_t siptag_retry_after_str;

extern msg_hclass_t sip_timestamp_class[];

/**@ingroup sip_timestamp
 * Tag for @ref sip_timestamp "Timestamp header" object.
 */
EXPORT tag_typedef_t siptag_timestamp_ref;
tag_typedef_t siptag_timestamp;
/**@ingroup sip_timestamp
 * Tag for string with @ref sip_timestamp "Timestamp header" value.
 */
EXPORT tag_typedef_t siptag_timestamp_str_ref;
tag_typedef_t siptag_timestamp_str;

extern msg_hclass_t sip_min_expires_class[];

/**@ingroup sip_min_expires
 * Tag for @ref sip_min_expires "Min-Expires header" object.
 */
EXPORT tag_typedef_t siptag_min_expires_ref;
tag_typedef_t siptag_min_expires;
/**@ingroup sip_min_expires
 * Tag for string with @ref sip_min_expires "Min-Expires header" value.
 */
EXPORT tag_typedef_t siptag_min_expires_str_ref;
tag_typedef_t siptag_min_expires_str;

extern msg_hclass_t sip_subject_class[];

/**@ingroup sip_subject
 * Tag for @ref sip_subject "Subject header" object.
 */
EXPORT tag_typedef_t siptag_subject_ref;
tag_typedef_t siptag_subject;
/**@ingroup sip_subject
 * Tag for string with @ref sip_subject "Subject header" value.
 */
EXPORT tag_typedef_t siptag_subject_str_ref;
tag_typedef_t siptag_subject_str;

extern msg_hclass_t sip_priority_class[];

/**@ingroup sip_priority
 * Tag for @ref sip_priority "Priority header" object.
 */
EXPORT tag_typedef_t siptag_priority_ref;
tag_typedef_t siptag_priority;
/**@ingroup sip_priority
 * Tag for string with @ref sip_priority "Priority header" value.
 */
EXPORT tag_typedef_t siptag_priority_str_ref;
tag_typedef_t siptag_priority_str;

extern msg_hclass_t sip_call_info_class[];

/**@ingroup sip_call_info
 * Tag for @ref sip_call_info "Call-Info header" object.
 */
EXPORT tag_typedef_t siptag_call_info_ref;
tag_typedef_t siptag_call_info;
/**@ingroup sip_call_info
 * Tag for string with @ref sip_call_info "Call-Info header" value.
 */
EXPORT tag_typedef_t siptag_call_info_str_ref;
tag_typedef_t siptag_call_info_str;

extern msg_hclass_t sip_organization_class[];

/**@ingroup sip_organization
 * Tag for @ref sip_organization "Organization header" object.
 */
EXPORT tag_typedef_t siptag_organization_ref;
tag_typedef_t siptag_organization;
/**@ingroup sip_organization
 * Tag for string with @ref sip_organization "Organization header" value.
 */
EXPORT tag_typedef_t siptag_organization_str_ref;
tag_typedef_t siptag_organization_str;

extern msg_hclass_t sip_server_class[];

/**@ingroup sip_server
 * Tag for @ref sip_server "Server header" object.
 */
EXPORT tag_typedef_t siptag_server_ref;
tag_typedef_t siptag_server;
/**@ingroup sip_server
 * Tag for string with @ref sip_server "Server header" value.
 */
EXPORT tag_typedef_t siptag_server_str_ref;
tag_typedef_t siptag_server_str;

extern msg_hclass_t sip_user_agent_class[];

/**@ingroup sip_user_agent
 * Tag for @ref sip_user_agent "User-Agent header" object.
 */
EXPORT tag_typedef_t siptag_user_agent_ref;
tag_typedef_t siptag_user_agent;
/**@ingroup sip_user_agent
 * Tag for string with @ref sip_user_agent "User-Agent header" value.
 */
EXPORT tag_typedef_t siptag_user_agent_str_ref;
tag_typedef_t siptag_user_agent_str;

extern msg_hclass_t sip_in_reply_to_class[];

/**@ingroup sip_in_reply_to
 * Tag for @ref sip_in_reply_to "In-Reply-To header" object.
 */
EXPORT tag_typedef_t siptag_in_reply_to_ref;
tag_typedef_t siptag_in_reply_to;
/**@ingroup sip_in_reply_to
 * Tag for string with @ref sip_in_reply_to "In-Reply-To header" value.
 */
EXPORT tag_typedef_t siptag_in_reply_to_str_ref;
tag_typedef_t siptag_in_reply_to_str;

extern msg_hclass_t sip_accept_class[];

/**@ingroup sip_accept
 * Tag for @ref sip_accept "Accept header" object.
 */
EXPORT tag_typedef_t siptag_accept_ref;
tag_typedef_t siptag_accept;
/**@ingroup sip_accept
 * Tag for string with @ref sip_accept "Accept header" value.
 */
EXPORT tag_typedef_t siptag_accept_str_ref;
tag_typedef_t siptag_accept_str;

extern msg_hclass_t sip_accept_encoding_class[];

/**@ingroup sip_accept_encoding
 * Tag for @ref sip_accept_encoding "Accept-Encoding header" object.
 */
EXPORT tag_typedef_t siptag_accept_encoding_ref;
tag_typedef_t siptag_accept_encoding;
/**@ingroup sip_accept_encoding
 * Tag for string with @ref sip_accept_encoding "Accept-Encoding header" value.
 */
EXPORT tag_typedef_t siptag_accept_encoding_str_ref;
tag_typedef_t siptag_accept_encoding_str;

extern msg_hclass_t sip_accept_language_class[];

/**@ingroup sip_accept_language
 * Tag for @ref sip_accept_language "Accept-Language header" object.
 */
EXPORT tag_typedef_t siptag_accept_language_ref;
tag_typedef_t siptag_accept_language;
/**@ingroup sip_accept_language
 * Tag for string with @ref sip_accept_language "Accept-Language header" value.
 */
EXPORT tag_typedef_t siptag_accept_language_str_ref;
tag_typedef_t siptag_accept_language_str;

extern msg_hclass_t sip_allow_class[];

/**@ingroup sip_allow
 * Tag for @ref sip_allow "Allow header" object.
 */
EXPORT tag_typedef_t siptag_allow_ref;
tag_typedef_t siptag_allow;
/**@ingroup sip_allow
 * Tag for string with @ref sip_allow "Allow header" value.
 */
EXPORT tag_typedef_t siptag_allow_str_ref;
tag_typedef_t siptag_allow_str;

extern msg_hclass_t sip_require_class[];

/**@ingroup sip_require
 * Tag for @ref sip_require "Require header" object.
 */
EXPORT tag_typedef_t siptag_require_ref;
tag_typedef_t siptag_require;
/**@ingroup sip_require
 * Tag for string with @ref sip_require "Require header" value.
 */
EXPORT tag_typedef_t siptag_require_str_ref;
tag_typedef_t siptag_require_str;

extern msg_hclass_t sip_supported_class[];

/**@ingroup sip_supported
 * Tag for @ref sip_supported "Supported header" object.
 */
EXPORT tag_typedef_t siptag_supported_ref;
tag_typedef_t siptag_supported;
/**@ingroup sip_supported
 * Tag for string with @ref sip_supported "Supported header" value.
 */
EXPORT tag_typedef_t siptag_supported_str_ref;
tag_typedef_t siptag_supported_str;

extern msg_hclass_t sip_unsupported_class[];

/**@ingroup sip_unsupported
 * Tag for @ref sip_unsupported "Unsupported header" object.
 */
EXPORT tag_typedef_t siptag_unsupported_ref;
tag_typedef_t siptag_unsupported;
/**@ingroup sip_unsupported
 * Tag for string with @ref sip_unsupported "Unsupported header" value.
 */
EXPORT tag_typedef_t siptag_unsupported_str_ref;
tag_typedef_t siptag_unsupported_str;

extern msg_hclass_t sip_event_class[];

/**@ingroup sip_event
 * Tag for @ref sip_event "Event header" object.
 */
EXPORT tag_typedef_t siptag_event_ref;
tag_typedef_t siptag_event;
/**@ingroup sip_event
 * Tag for string with @ref sip_event "Event header" value.
 */
EXPORT tag_typedef_t siptag_event_str_ref;
tag_typedef_t siptag_event_str;

extern msg_hclass_t sip_allow_events_class[];

/**@ingroup sip_allow_events
 * Tag for @ref sip_allow_events "Allow-Events header" object.
 */
EXPORT tag_typedef_t siptag_allow_events_ref;
tag_typedef_t siptag_allow_events;
/**@ingroup sip_allow_events
 * Tag for string with @ref sip_allow_events "Allow-Events header" value.
 */
EXPORT tag_typedef_t siptag_allow_events_str_ref;
tag_typedef_t siptag_allow_events_str;

extern msg_hclass_t sip_subscription_state_class[];

/**@ingroup sip_subscription_state
 * Tag for @ref sip_subscription_state "Subscription-State header" object.
 */
EXPORT tag_typedef_t siptag_subscription_state_ref;
tag_typedef_t siptag_subscription_state;
/**@ingroup sip_subscription_state
 * Tag for string with @ref sip_subscription_state "Subscription-State header" value.
 */
EXPORT tag_typedef_t siptag_subscription_state_str_ref;
tag_typedef_t siptag_subscription_state_str;

extern msg_hclass_t sip_proxy_authenticate_class[];

/**@ingroup sip_proxy_authenticate
 * Tag for @ref sip_proxy_authenticate "Proxy-Authenticate header" object.
 */
EXPORT tag_typedef_t siptag_proxy_authenticate_ref;
tag_typedef_t siptag_proxy_authenticate;
/**@ingroup sip_proxy_authenticate
 * Tag for string with @ref sip_proxy_authenticate "Proxy-Authenticate header" value.
 */
EXPORT tag_typedef_t siptag_proxy_authenticate_str_ref;
tag_typedef_t siptag_proxy_authenticate_str;

extern msg_hclass_t sip_proxy_authentication_info_class[];

/**@ingroup sip_proxy_authentication_info
 * Tag for @ref sip_proxy_authentication_info "Proxy-Authentication-Info header" object.
 */
EXPORT tag_typedef_t siptag_proxy_authentication_info_ref;
tag_typedef_t siptag_proxy_authentication_info;
/**@ingroup sip_proxy_authentication_info
 * Tag for string with @ref sip_proxy_authentication_info "Proxy-Authentication-Info header" value.
 */
EXPORT tag_typedef_t siptag_proxy_authentication_info_str_ref;
tag_typedef_t siptag_proxy_authentication_info_str;

extern msg_hclass_t sip_proxy_authorization_class[];

/**@ingroup sip_proxy_authorization
 * Tag for @ref sip_proxy_authorization "Proxy-Authorization header" object.
 */
EXPORT tag_typedef_t siptag_proxy_authorization_ref;
tag_typedef_t siptag_proxy_authorization;
/**@ingroup sip_proxy_authorization
 * Tag for string with @ref sip_proxy_authorization "Proxy-Authorization header" value.
 */
EXPORT tag_typedef_t siptag_proxy_authorization_str_ref;
tag_typedef_t siptag_proxy_authorization_str;

extern msg_hclass_t sip_authorization_class[];

/**@ingroup sip_authorization
 * Tag for @ref sip_authorization "Authorization header" object.
 */
EXPORT tag_typedef_t siptag_authorization_ref;
tag_typedef_t siptag_authorization;
/**@ingroup sip_authorization
 * Tag for string with @ref sip_authorization "Authorization header" value.
 */
EXPORT tag_typedef_t siptag_authorization_str_ref;
tag_typedef_t siptag_authorization_str;

extern msg_hclass_t sip_www_authenticate_class[];

/**@ingroup sip_www_authenticate
 * Tag for @ref sip_www_authenticate "WWW-Authenticate header" object.
 */
EXPORT tag_typedef_t siptag_www_authenticate_ref;
tag_typedef_t siptag_www_authenticate;
/**@ingroup sip_www_authenticate
 * Tag for string with @ref sip_www_authenticate "WWW-Authenticate header" value.
 */
EXPORT tag_typedef_t siptag_www_authenticate_str_ref;
tag_typedef_t siptag_www_authenticate_str;

extern msg_hclass_t sip_authentication_info_class[];

/**@ingroup sip_authentication_info
 * Tag for @ref sip_authentication_info "Authentication-Info header" object.
 */
EXPORT tag_typedef_t siptag_authentication_info_ref;
tag_typedef_t siptag_authentication_info;
/**@ingroup sip_authentication_info
 * Tag for string with @ref sip_authentication_info "Authentication-Info header" value.
 */
EXPORT tag_typedef_t siptag_authentication_info_str_ref;
tag_typedef_t siptag_authentication_info_str;

extern msg_hclass_t sip_error_info_class[];

/**@ingroup sip_error_info
 * Tag for @ref sip_error_info "Error-Info header" object.
 */
EXPORT tag_typedef_t siptag_error_info_ref;
tag_typedef_t siptag_error_info;
/**@ingroup sip_error_info
 * Tag for string with @ref sip_error_info "Error-Info header" value.
 */
EXPORT tag_typedef_t siptag_error_info_str_ref;
tag_typedef_t siptag_error_info_str;

extern msg_hclass_t sip_warning_class[];

/**@ingroup sip_warning
 * Tag for @ref sip_warning "Warning header" object.
 */
EXPORT tag_typedef_t siptag_warning_ref;
tag_typedef_t siptag_warning;
/**@ingroup sip_warning
 * Tag for string with @ref sip_warning "Warning header" value.
 */
EXPORT tag_typedef_t siptag_warning_str_ref;
tag_typedef_t siptag_warning_str;

extern msg_hclass_t sip_refer_to_class[];

/**@ingroup sip_refer_to
 * Tag for @ref sip_refer_to "Refer-To header" object.
 */
EXPORT tag_typedef_t siptag_refer_to_ref;
tag_typedef_t siptag_refer_to;
/**@ingroup sip_refer_to
 * Tag for string with @ref sip_refer_to "Refer-To header" value.
 */
EXPORT tag_typedef_t siptag_refer_to_str_ref;
tag_typedef_t siptag_refer_to_str;

extern msg_hclass_t sip_referred_by_class[];

/**@ingroup sip_referred_by
 * Tag for @ref sip_referred_by "Referred-By header" object.
 */
EXPORT tag_typedef_t siptag_referred_by_ref;
tag_typedef_t siptag_referred_by;
/**@ingroup sip_referred_by
 * Tag for string with @ref sip_referred_by "Referred-By header" value.
 */
EXPORT tag_typedef_t siptag_referred_by_str_ref;
tag_typedef_t siptag_referred_by_str;

extern msg_hclass_t sip_replaces_class[];

/**@ingroup sip_replaces
 * Tag for @ref sip_replaces "Replaces header" object.
 */
EXPORT tag_typedef_t siptag_replaces_ref;
tag_typedef_t siptag_replaces;
/**@ingroup sip_replaces
 * Tag for string with @ref sip_replaces "Replaces header" value.
 */
EXPORT tag_typedef_t siptag_replaces_str_ref;
tag_typedef_t siptag_replaces_str;

extern msg_hclass_t sip_session_expires_class[];

/**@ingroup sip_session_expires
 * Tag for @ref sip_session_expires "Session-Expires header" object.
 */
EXPORT tag_typedef_t siptag_session_expires_ref;
tag_typedef_t siptag_session_expires;
/**@ingroup sip_session_expires
 * Tag for string with @ref sip_session_expires "Session-Expires header" value.
 */
EXPORT tag_typedef_t siptag_session_expires_str_ref;
tag_typedef_t siptag_session_expires_str;

extern msg_hclass_t sip_min_se_class[];

/**@ingroup sip_min_se
 * Tag for @ref sip_min_se "Min-SE header" object.
 */
EXPORT tag_typedef_t siptag_min_se_ref;
tag_typedef_t siptag_min_se;
/**@ingroup sip_min_se
 * Tag for string with @ref sip_min_se "Min-SE header" value.
 */
EXPORT tag_typedef_t siptag_min_se_str_ref;
tag_typedef_t siptag_min_se_str;

extern msg_hclass_t sip_path_class[];

/**@ingroup sip_path
 * Tag for @ref sip_path "Path header" object.
 */
EXPORT tag_typedef_t siptag_path_ref;
tag_typedef_t siptag_path;
/**@ingroup sip_path
 * Tag for string with @ref sip_path "Path header" value.
 */
EXPORT tag_typedef_t siptag_path_str_ref;
tag_typedef_t siptag_path_str;

extern msg_hclass_t sip_service_route_class[];

/**@ingroup sip_service_route
 * Tag for @ref sip_service_route "Service-Route header" object.
 */
EXPORT tag_typedef_t siptag_service_route_ref;
tag_typedef_t siptag_service_route;
/**@ingroup sip_service_route
 * Tag for string with @ref sip_service_route "Service-Route header" value.
 */
EXPORT tag_typedef_t siptag_service_route_str_ref;
tag_typedef_t siptag_service_route_str;

extern msg_hclass_t sip_reason_class[];

/**@ingroup sip_reason
 * Tag for @ref sip_reason "Reason header" object.
 */
EXPORT tag_typedef_t siptag_reason_ref;
tag_typedef_t siptag_reason;
/**@ingroup sip_reason
 * Tag for string with @ref sip_reason "Reason header" value.
 */
EXPORT tag_typedef_t siptag_reason_str_ref;
tag_typedef_t siptag_reason_str;

extern msg_hclass_t sip_security_client_class[];

/**@ingroup sip_security_client
 * Tag for @ref sip_security_client "Security-Client header" object.
 */
EXPORT tag_typedef_t siptag_security_client_ref;
tag_typedef_t siptag_security_client;
/**@ingroup sip_security_client
 * Tag for string with @ref sip_security_client "Security-Client header" value.
 */
EXPORT tag_typedef_t siptag_security_client_str_ref;
tag_typedef_t siptag_security_client_str;

extern msg_hclass_t sip_security_server_class[];

/**@ingroup sip_security_server
 * Tag for @ref sip_security_server "Security-Server header" object.
 */
EXPORT tag_typedef_t siptag_security_server_ref;
tag_typedef_t siptag_security_server;
/**@ingroup sip_security_server
 * Tag for string with @ref sip_security_server "Security-Server header" value.
 */
EXPORT tag_typedef_t siptag_security_server_str_ref;
tag_typedef_t siptag_security_server_str;

extern msg_hclass_t sip_security_verify_class[];

/**@ingroup sip_security_verify
 * Tag for @ref sip_security_verify "Security-Verify header" object.
 */
EXPORT tag_typedef_t siptag_security_verify_ref;
tag_typedef_t siptag_security_verify;
/**@ingroup sip_security_verify
 * Tag for string with @ref sip_security_verify "Security-Verify header" value.
 */
EXPORT tag_typedef_t siptag_security_verify_str_ref;
tag_typedef_t siptag_security_verify_str;

extern msg_hclass_t sip_privacy_class[];

/**@ingroup sip_privacy
 * Tag for @ref sip_privacy "Privacy header" object.
 */
EXPORT tag_typedef_t siptag_privacy_ref;
tag_typedef_t siptag_privacy;
/**@ingroup sip_privacy
 * Tag for string with @ref sip_privacy "Privacy header" value.
 */
EXPORT tag_typedef_t siptag_privacy_str_ref;
tag_typedef_t siptag_privacy_str;

extern msg_hclass_t sip_etag_class[];

/**@ingroup sip_etag
 * Tag for @ref sip_etag "SIP-ETag header" object.
 */
EXPORT tag_typedef_t siptag_etag_ref;
tag_typedef_t siptag_etag;
/**@ingroup sip_etag
 * Tag for string with @ref sip_etag "SIP-ETag header" value.
 */
EXPORT tag_typedef_t siptag_etag_str_ref;
tag_typedef_t siptag_etag_str;

extern msg_hclass_t sip_if_match_class[];

/**@ingroup sip_if_match
 * Tag for @ref sip_if_match "SIP-If-Match header" object.
 */
EXPORT tag_typedef_t siptag_if_match_ref;
tag_typedef_t siptag_if_match;
/**@ingroup sip_if_match
 * Tag for string with @ref sip_if_match "SIP-If-Match header" value.
 */
EXPORT tag_typedef_t siptag_if_match_str_ref;
tag_typedef_t siptag_if_match_str;

extern msg_hclass_t sip_mime_version_class[];

/**@ingroup sip_mime_version
 * Tag for @ref sip_mime_version "MIME-Version header" object.
 */
EXPORT tag_typedef_t siptag_mime_version_ref;
tag_typedef_t siptag_mime_version;
/**@ingroup sip_mime_version
 * Tag for string with @ref sip_mime_version "MIME-Version header" value.
 */
EXPORT tag_typedef_t siptag_mime_version_str_ref;
tag_typedef_t siptag_mime_version_str;

extern msg_hclass_t sip_content_type_class[];

/**@ingroup sip_content_type
 * Tag for @ref sip_content_type "Content-Type header" object.
 */
EXPORT tag_typedef_t siptag_content_type_ref;
tag_typedef_t siptag_content_type;
/**@ingroup sip_content_type
 * Tag for string with @ref sip_content_type "Content-Type header" value.
 */
EXPORT tag_typedef_t siptag_content_type_str_ref;
tag_typedef_t siptag_content_type_str;

extern msg_hclass_t sip_content_encoding_class[];

/**@ingroup sip_content_encoding
 * Tag for @ref sip_content_encoding "Content-Encoding header" object.
 */
EXPORT tag_typedef_t siptag_content_encoding_ref;
tag_typedef_t siptag_content_encoding;
/**@ingroup sip_content_encoding
 * Tag for string with @ref sip_content_encoding "Content-Encoding header" value.
 */
EXPORT tag_typedef_t siptag_content_encoding_str_ref;
tag_typedef_t siptag_content_encoding_str;

extern msg_hclass_t sip_content_language_class[];

/**@ingroup sip_content_language
 * Tag for @ref sip_content_language "Content-Language header" object.
 */
EXPORT tag_typedef_t siptag_content_language_ref;
tag_typedef_t siptag_content_language;
/**@ingroup sip_content_language
 * Tag for string with @ref sip_content_language "Content-Language header" value.
 */
EXPORT tag_typedef_t siptag_content_language_str_ref;
tag_typedef_t siptag_content_language_str;

extern msg_hclass_t sip_content_disposition_class[];

/**@ingroup sip_content_disposition
 * Tag for @ref sip_content_disposition "Content-Disposition header" object.
 */
EXPORT tag_typedef_t siptag_content_disposition_ref;
tag_typedef_t siptag_content_disposition;
/**@ingroup sip_content_disposition
 * Tag for string with @ref sip_content_disposition "Content-Disposition header" value.
 */
EXPORT tag_typedef_t siptag_content_disposition_str_ref;
tag_typedef_t siptag_content_disposition_str;

extern msg_hclass_t sip_content_length_class[];

/**@ingroup sip_content_length
 * Tag for @ref sip_content_length "Content-Length header" object.
 */
EXPORT tag_typedef_t siptag_content_length_ref;
tag_typedef_t siptag_content_length;
/**@ingroup sip_content_length
 * Tag for string with @ref sip_content_length "Content-Length header" value.
 */
EXPORT tag_typedef_t siptag_content_length_str_ref;
tag_typedef_t siptag_content_length_str;

extern msg_hclass_t sip_refer_sub_class[];

/**@ingroup sip_refer_sub
 * Tag for @ref sip_refer_sub "Refer-Sub header" object.
 */
EXPORT tag_typedef_t siptag_refer_sub_ref;
tag_typedef_t siptag_refer_sub;
/**@ingroup sip_refer_sub
 * Tag for string with @ref sip_refer_sub "Refer-Sub header" value.
 */
EXPORT tag_typedef_t siptag_refer_sub_str_ref;
tag_typedef_t siptag_refer_sub_str;

extern msg_hclass_t sip_alert_info_class[];

/**@ingroup sip_alert_info
 * Tag for @ref sip_alert_info "Alert-Info header" object.
 */
EXPORT tag_typedef_t siptag_alert_info_ref;
tag_typedef_t siptag_alert_info;
/**@ingroup sip_alert_info
 * Tag for string with @ref sip_alert_info "Alert-Info header" value.
 */
EXPORT tag_typedef_t siptag_alert_info_str_ref;
tag_typedef_t siptag_alert_info_str;

extern msg_hclass_t sip_reply_to_class[];

/**@ingroup sip_reply_to
 * Tag for @ref sip_reply_to "Reply-To header" object.
 */
EXPORT tag_typedef_t siptag_reply_to_ref;
tag_typedef_t siptag_reply_to;
/**@ingroup sip_reply_to
 * Tag for string with @ref sip_reply_to "Reply-To header" value.
 */
EXPORT tag_typedef_t siptag_reply_to_str_ref;
tag_typedef_t siptag_reply_to_str;

extern msg_hclass_t sip_remote_party_id_class[];

/**@ingroup sip_remote_party_id
 * Tag for @ref sip_remote_party_id "Remote-Party-ID header" object.
 */
EXPORT tag_typedef_t siptag_remote_party_id_ref;
tag_typedef_t siptag_remote_party_id;
/**@ingroup sip_remote_party_id
 * Tag for string with @ref sip_remote_party_id "Remote-Party-ID header" value.
 */
EXPORT tag_typedef_t siptag_remote_party_id_str_ref;
tag_typedef_t siptag_remote_party_id_str;

extern msg_hclass_t sip_p_asserted_identity_class[];

/**@ingroup sip_p_asserted_identity
 * Tag for @ref sip_p_asserted_identity "P-Asserted-Identity header" object.
 */
EXPORT tag_typedef_t siptag_p_asserted_identity_ref;
tag_typedef_t siptag_p_asserted_identity;
/**@ingroup sip_p_asserted_identity
 * Tag for string with @ref sip_p_asserted_identity "P-Asserted-Identity header" value.
 */
EXPORT tag_typedef_t siptag_p_asserted_identity_str_ref;
tag_typedef_t siptag_p_asserted_identity_str;

extern msg_hclass_t sip_p_preferred_identity_class[];

/**@ingroup sip_p_preferred_identity
 * Tag for @ref sip_p_preferred_identity "P-Preferred-Identity header" object.
 */
EXPORT tag_typedef_t siptag_p_preferred_identity_ref;
tag_typedef_t siptag_p_preferred_identity;
/**@ingroup sip_p_preferred_identity
 * Tag for string with @ref sip_p_preferred_identity "P-Preferred-Identity header" value.
 */
EXPORT tag_typedef_t siptag_p_preferred_identity_str_ref;
tag_typedef_t siptag_p_preferred_identity_str;

#if SU_HAVE_EXPERIMENTAL
#if SU_HAVE_EXPERIMENTAL
extern msg_hclass_t sip_suppress_body_if_match_class[];

/**@ingroup sip_suppress_body_if_match
 * Tag for @ref sip_suppress_body_if_match "Suppress-Body-If-Match header" object.
 */
EXPORT tag_typedef_t siptag_suppress_body_if_match_ref;
tag_typedef_t siptag_suppress_body_if_match;
/**@ingroup sip_suppress_body_if_match
 * Tag for string with @ref sip_suppress_body_if_match "Suppress-Body-If-Match header" value.
 */
EXPORT tag_typedef_t siptag_suppress_body_if_match_str_ref;
tag_typedef_t siptag_suppress_body_if_match_str;

#endif /* SU_HAVE_EXPERIMENTAL */
#endif /* SU_HAVE_EXPERIMENTAL */
#if SU_HAVE_EXPERIMENTAL
#if SU_HAVE_EXPERIMENTAL
extern msg_hclass_t sip_suppress_notify_if_match_class[];

/**@ingroup sip_suppress_notify_if_match
 * Tag for @ref sip_suppress_notify_if_match "Suppress-Notify-If-Match header" object.
 */
EXPORT tag_typedef_t siptag_suppress_notify_if_match_ref;
tag_typedef_t siptag_suppress_notify_if_match;
/**@ingroup sip_suppress_notify_if_match
 * Tag for string with @ref sip_suppress_notify_if_match "Suppress-Notify-If-Match header" value.
 */
EXPORT tag_typedef_t siptag_suppress_notify_if_match_str_ref;
tag_typedef_t siptag_suppress_notify_if_match_str;

#endif /* SU_HAVE_EXPERIMENTAL */
#endif /* SU_HAVE_EXPERIMENTAL */
extern msg_hclass_t sip_unknown_class[];

/**@ingroup sip_unknown
 * Tag for @ref sip_unknown "unknown headers" object.
 */
EXPORT tag_typedef_t siptag_unknown_ref;
tag_typedef_t siptag_unknown;
/**@ingroup sip_unknown
 * Tag for string with @ref sip_unknown "unknown headers" value.
 */
EXPORT tag_typedef_t siptag_unknown_str_ref;
tag_typedef_t siptag_unknown_str;

extern msg_hclass_t sip_error_class[];

/**@ingroup sip_error
 * Tag for @ref sip_error "erroneous headers" object.
 */
EXPORT tag_typedef_t siptag_error_ref;
tag_typedef_t siptag_error;
/**@ingroup sip_error
 * Tag for string with @ref sip_error "erroneous headers" value.
 */
EXPORT tag_typedef_t siptag_error_str_ref;
tag_typedef_t siptag_error_str;

extern msg_hclass_t sip_separator_class[];

/**@ingroup sip_separator
 * Tag for @ref sip_separator "separator line between headers and body" object.
 */
EXPORT tag_typedef_t siptag_separator_ref;
tag_typedef_t siptag_separator;
/**@ingroup sip_separator
 * Tag for string with @ref sip_separator "separator line between headers and body" value.
 */
EXPORT tag_typedef_t siptag_separator_str_ref;
tag_typedef_t siptag_separator_str;

extern msg_hclass_t sip_payload_class[];

/**@ingroup sip_payload
 * Tag for @ref sip_payload "message payload" object.
 */
EXPORT tag_typedef_t siptag_payload_ref;
tag_typedef_t siptag_payload;
/**@ingroup sip_payload
 * Tag for string with @ref sip_payload "message payload" value.
 */
EXPORT tag_typedef_t siptag_payload_str_ref;
tag_typedef_t siptag_payload_str;

/** List of all tags for SIP headers */
tag_type_t sip_tag_list[] =
{
  siptag_request,
  siptag_status,
  siptag_via,
  siptag_route,
  siptag_record_route,
  siptag_max_forwards,
  siptag_proxy_require,
  siptag_from,
  siptag_to,
  siptag_call_id,
  siptag_cseq,
  siptag_contact,
  siptag_rseq,
  siptag_rack,
  siptag_request_disposition,
  siptag_accept_contact,
  siptag_reject_contact,
  siptag_expires,
  siptag_date,
  siptag_retry_after,
  siptag_timestamp,
  siptag_min_expires,
  siptag_subject,
  siptag_priority,
  siptag_call_info,
  siptag_organization,
  siptag_server,
  siptag_user_agent,
  siptag_in_reply_to,
  siptag_accept,
  siptag_accept_encoding,
  siptag_accept_language,
  siptag_allow,
  siptag_require,
  siptag_supported,
  siptag_unsupported,
  siptag_event,
  siptag_allow_events,
  siptag_subscription_state,
  siptag_proxy_authenticate,
  siptag_proxy_authentication_info,
  siptag_proxy_authorization,
  siptag_authorization,
  siptag_www_authenticate,
  siptag_authentication_info,
  siptag_error_info,
  siptag_warning,
  siptag_refer_to,
  siptag_referred_by,
  siptag_replaces,
  siptag_session_expires,
  siptag_min_se,
  siptag_path,
  siptag_service_route,
  siptag_reason,
  siptag_security_client,
  siptag_security_server,
  siptag_security_verify,
  siptag_privacy,
  siptag_etag,
  siptag_if_match,
  siptag_mime_version,
  siptag_content_type,
  siptag_content_encoding,
  siptag_content_language,
  siptag_content_disposition,
  siptag_content_length,
  siptag_refer_sub,
  siptag_alert_info,
  siptag_reply_to,
  siptag_remote_party_id,
  siptag_p_asserted_identity,
  siptag_p_preferred_identity,
#if SU_HAVE_EXPERIMENTAL
#if SU_HAVE_EXPERIMENTAL
  siptag_suppress_body_if_match,
  siptag_suppress_notify_if_match,
#endif /* SU_HAVE_EXPERIMENTAL */
#endif /* SU_HAVE_EXPERIMENTAL */
  siptag_unknown,
  siptag_error,
  siptag_separator,
  siptag_payload,
  NULL
};

/** List of all string tags for SIP headers  */
tag_type_t sip_tag_str_list[] =
{
  siptag_request_str,
  siptag_status_str,
  siptag_via_str,
  siptag_route_str,
  siptag_record_route_str,
  siptag_max_forwards_str,
  siptag_proxy_require_str,
  siptag_from_str,
  siptag_to_str,
  siptag_call_id_str,
  siptag_cseq_str,
  siptag_contact_str,
  siptag_rseq_str,
  siptag_rack_str,
  siptag_request_disposition_str,
  siptag_accept_contact_str,
  siptag_reject_contact_str,
  siptag_expires_str,
  siptag_date_str,
  siptag_retry_after_str,
  siptag_timestamp_str,
  siptag_min_expires_str,
  siptag_subject_str,
  siptag_priority_str,
  siptag_call_info_str,
  siptag_organization_str,
  siptag_server_str,
  siptag_user_agent_str,
  siptag_in_reply_to_str,
  siptag_accept_str,
  siptag_accept_encoding_str,
  siptag_accept_language_str,
  siptag_allow_str,
  siptag_require_str,
  siptag_supported_str,
  siptag_unsupported_str,
  siptag_event_str,
  siptag_allow_events_str,
  siptag_subscription_state_str,
  siptag_proxy_authenticate_str,
  siptag_proxy_authentication_info_str,
  siptag_proxy_authorization_str,
  siptag_authorization_str,
  siptag_www_authenticate_str,
  siptag_authentication_info_str,
  siptag_error_info_str,
  siptag_warning_str,
  siptag_refer_to_str,
  siptag_referred_by_str,
  siptag_replaces_str,
  siptag_session_expires_str,
  siptag_min_se_str,
  siptag_path_str,
  siptag_service_route_str,
  siptag_reason_str,
  siptag_security_client_str,
  siptag_security_server_str,
  siptag_security_verify_str,
  siptag_privacy_str,
  siptag_etag_str,
  siptag_if_match_str,
  siptag_mime_version_str,
  siptag_content_type_str,
  siptag_content_encoding_str,
  siptag_content_language_str,
  siptag_content_disposition_str,
  siptag_content_length_str,
  siptag_refer_sub_str,
  siptag_alert_info_str,
  siptag_reply_to_str,
  siptag_remote_party_id_str,
  siptag_p_asserted_identity_str,
  siptag_p_preferred_identity_str,
#if SU_HAVE_EXPERIMENTAL
#if SU_HAVE_EXPERIMENTAL
  siptag_suppress_body_if_match_str,
  siptag_suppress_notify_if_match_str,
#endif /* SU_HAVE_EXPERIMENTAL */
#endif /* SU_HAVE_EXPERIMENTAL */
  siptag_unknown_str,
  siptag_error_str,
  siptag_separator_str,
  siptag_payload_str,
  NULL
};


#include <windows.h>

BOOL WINAPI DllMain(HINSTANCE hInst, DWORD fwdReason, LPVOID fImpLoad)
{
  tag_typedef_t _siptag_mime_version = SIPHDRTAG_TYPEDEF(mime_version);
  tag_typedef_t _siptag_mime_version_ref =
    REFTAG_TYPEDEF(siptag_mime_version);
  tag_typedef_t _siptag_subject = SIPHDRTAG_TYPEDEF(subject);
  tag_typedef_t _siptag_subject_ref =
    REFTAG_TYPEDEF(siptag_subject);
  tag_typedef_t _siptag_security_server = SIPHDRTAG_TYPEDEF(security_server);
  tag_typedef_t _siptag_security_server_ref =
    REFTAG_TYPEDEF(siptag_security_server);
  tag_typedef_t _siptag_cseq = SIPHDRTAG_TYPEDEF(cseq);
  tag_typedef_t _siptag_cseq_ref =
    REFTAG_TYPEDEF(siptag_cseq);
  tag_typedef_t _siptag_remote_party_id = SIPHDRTAG_TYPEDEF(remote_party_id);
  tag_typedef_t _siptag_remote_party_id_ref =
    REFTAG_TYPEDEF(siptag_remote_party_id);
  tag_typedef_t _siptag_authentication_info = SIPHDRTAG_TYPEDEF(authentication_info);
  tag_typedef_t _siptag_authentication_info_ref =
    REFTAG_TYPEDEF(siptag_authentication_info);
  tag_typedef_t _siptag_accept = SIPHDRTAG_TYPEDEF(accept);
  tag_typedef_t _siptag_accept_ref =
    REFTAG_TYPEDEF(siptag_accept);
  tag_typedef_t _siptag_rack = SIPHDRTAG_TYPEDEF(rack);
  tag_typedef_t _siptag_rack_ref =
    REFTAG_TYPEDEF(siptag_rack);
  tag_typedef_t _siptag_error = SIPHDRTAG_TYPEDEF(error);
  tag_typedef_t _siptag_error_ref =
    REFTAG_TYPEDEF(siptag_error);
  tag_typedef_t _siptag_suppress_notify_if_match_str = SIPSTRTAG_TYPEDEF(suppress_notify_if_match);
  tag_typedef_t _siptag_suppress_notify_if_match_str_ref =
    REFTAG_TYPEDEF(siptag_suppress_notify_if_match_str);
  tag_typedef_t _siptag_any = NSTAG_TYPEDEF(*);
  tag_typedef_t _siptag_any_ref =
    REFTAG_TYPEDEF(siptag_any);
  tag_typedef_t _siptag_suppress_body_if_match_str = SIPSTRTAG_TYPEDEF(suppress_body_if_match);
  tag_typedef_t _siptag_suppress_body_if_match_str_ref =
    REFTAG_TYPEDEF(siptag_suppress_body_if_match_str);
  tag_typedef_t _siptag_proxy_authenticate_str = SIPSTRTAG_TYPEDEF(proxy_authenticate);
  tag_typedef_t _siptag_proxy_authenticate_str_ref =
    REFTAG_TYPEDEF(siptag_proxy_authenticate_str);
  tag_typedef_t _siptag_subscription_state_str = SIPSTRTAG_TYPEDEF(subscription_state);
  tag_typedef_t _siptag_subscription_state_str_ref =
    REFTAG_TYPEDEF(siptag_subscription_state_str);
  tag_typedef_t _siptag_replaces = SIPHDRTAG_TYPEDEF(replaces);
  tag_typedef_t _siptag_replaces_ref =
    REFTAG_TYPEDEF(siptag_replaces);
  tag_typedef_t _siptag_server = SIPHDRTAG_TYPEDEF(server);
  tag_typedef_t _siptag_server_ref =
    REFTAG_TYPEDEF(siptag_server);
  tag_typedef_t _siptag_remote_party_id_str = SIPSTRTAG_TYPEDEF(remote_party_id);
  tag_typedef_t _siptag_remote_party_id_str_ref =
    REFTAG_TYPEDEF(siptag_remote_party_id_str);
  tag_typedef_t _siptag_alert_info = SIPHDRTAG_TYPEDEF(alert_info);
  tag_typedef_t _siptag_alert_info_ref =
    REFTAG_TYPEDEF(siptag_alert_info);
  tag_typedef_t _siptag_content_language_str = SIPSTRTAG_TYPEDEF(content_language);
  tag_typedef_t _siptag_content_language_str_ref =
    REFTAG_TYPEDEF(siptag_content_language_str);
  tag_typedef_t _siptag_error_info = SIPHDRTAG_TYPEDEF(error_info);
  tag_typedef_t _siptag_error_info_ref =
    REFTAG_TYPEDEF(siptag_error_info);
  tag_typedef_t _siptag_www_authenticate_str = SIPSTRTAG_TYPEDEF(www_authenticate);
  tag_typedef_t _siptag_www_authenticate_str_ref =
    REFTAG_TYPEDEF(siptag_www_authenticate_str);
  tag_typedef_t _siptag_request = SIPHDRTAG_TYPEDEF(request);
  tag_typedef_t _siptag_request_ref =
    REFTAG_TYPEDEF(siptag_request);
  tag_typedef_t _siptag_unknown = SIPHDRTAG_TYPEDEF(unknown);
  tag_typedef_t _siptag_unknown_ref =
    REFTAG_TYPEDEF(siptag_unknown);
  tag_typedef_t _siptag_proxy_authentication_info_str = SIPSTRTAG_TYPEDEF(proxy_authentication_info);
  tag_typedef_t _siptag_proxy_authentication_info_str_ref =
    REFTAG_TYPEDEF(siptag_proxy_authentication_info_str);
  tag_typedef_t _siptag_proxy_authenticate = SIPHDRTAG_TYPEDEF(proxy_authenticate);
  tag_typedef_t _siptag_proxy_authenticate_ref =
    REFTAG_TYPEDEF(siptag_proxy_authenticate);
  tag_typedef_t _siptag_accept_language_str = SIPSTRTAG_TYPEDEF(accept_language);
  tag_typedef_t _siptag_accept_language_str_ref =
    REFTAG_TYPEDEF(siptag_accept_language_str);
  tag_typedef_t _siptag_call_info = SIPHDRTAG_TYPEDEF(call_info);
  tag_typedef_t _siptag_call_info_ref =
    REFTAG_TYPEDEF(siptag_call_info);
  tag_typedef_t _siptag_content_encoding_str = SIPSTRTAG_TYPEDEF(content_encoding);
  tag_typedef_t _siptag_content_encoding_str_ref =
    REFTAG_TYPEDEF(siptag_content_encoding_str);
  tag_typedef_t _siptag_subscription_state = SIPHDRTAG_TYPEDEF(subscription_state);
  tag_typedef_t _siptag_subscription_state_ref =
    REFTAG_TYPEDEF(siptag_subscription_state);
  tag_typedef_t _siptag_event = SIPHDRTAG_TYPEDEF(event);
  tag_typedef_t _siptag_event_ref =
    REFTAG_TYPEDEF(siptag_event);
  tag_typedef_t _siptag_service_route_str = SIPSTRTAG_TYPEDEF(service_route);
  tag_typedef_t _siptag_service_route_str_ref =
    REFTAG_TYPEDEF(siptag_service_route_str);
  tag_typedef_t _siptag_www_authenticate = SIPHDRTAG_TYPEDEF(www_authenticate);
  tag_typedef_t _siptag_www_authenticate_ref =
    REFTAG_TYPEDEF(siptag_www_authenticate);
  tag_typedef_t _siptag_accept_encoding_str = SIPSTRTAG_TYPEDEF(accept_encoding);
  tag_typedef_t _siptag_accept_encoding_str_ref =
    REFTAG_TYPEDEF(siptag_accept_encoding_str);
  tag_typedef_t _siptag_reject_contact = SIPHDRTAG_TYPEDEF(reject_contact);
  tag_typedef_t _siptag_reject_contact_ref =
    REFTAG_TYPEDEF(siptag_reject_contact);
  tag_typedef_t _siptag_accept_contact = SIPHDRTAG_TYPEDEF(accept_contact);
  tag_typedef_t _siptag_accept_contact_ref =
    REFTAG_TYPEDEF(siptag_accept_contact);
  tag_typedef_t _siptag_proxy_require_str = SIPSTRTAG_TYPEDEF(proxy_require);
  tag_typedef_t _siptag_proxy_require_str_ref =
    REFTAG_TYPEDEF(siptag_proxy_require_str);
  tag_typedef_t _siptag_end = TAG_TYPEDEF(tag_end, end);
  tag_typedef_t _siptag_end_ref =
    REFTAG_TYPEDEF(siptag_end);
  tag_typedef_t _siptag_refer_sub_str = SIPSTRTAG_TYPEDEF(refer_sub);
  tag_typedef_t _siptag_refer_sub_str_ref =
    REFTAG_TYPEDEF(siptag_refer_sub_str);
  tag_typedef_t _siptag_content_type_str = SIPSTRTAG_TYPEDEF(content_type);
  tag_typedef_t _siptag_content_type_str_ref =
    REFTAG_TYPEDEF(siptag_content_type_str);
  tag_typedef_t _siptag_unsupported_str = SIPSTRTAG_TYPEDEF(unsupported);
  tag_typedef_t _siptag_unsupported_str_ref =
    REFTAG_TYPEDEF(siptag_unsupported_str);
  tag_typedef_t _siptag_record_route_str = SIPSTRTAG_TYPEDEF(record_route);
  tag_typedef_t _siptag_record_route_str_ref =
    REFTAG_TYPEDEF(siptag_record_route_str);
  tag_typedef_t _siptag_content_length_str = SIPSTRTAG_TYPEDEF(content_length);
  tag_typedef_t _siptag_content_length_str_ref =
    REFTAG_TYPEDEF(siptag_content_length_str);
  tag_typedef_t _siptag_content_length = SIPHDRTAG_TYPEDEF(content_length);
  tag_typedef_t _siptag_content_length_ref =
    REFTAG_TYPEDEF(siptag_content_length);
  tag_typedef_t _siptag_session_expires = SIPHDRTAG_TYPEDEF(session_expires);
  tag_typedef_t _siptag_session_expires_ref =
    REFTAG_TYPEDEF(siptag_session_expires);
  tag_typedef_t _siptag_content_disposition_str = SIPSTRTAG_TYPEDEF(content_disposition);
  tag_typedef_t _siptag_content_disposition_str_ref =
    REFTAG_TYPEDEF(siptag_content_disposition_str);
  tag_typedef_t _siptag_proxy_authorization_str = SIPSTRTAG_TYPEDEF(proxy_authorization);
  tag_typedef_t _siptag_proxy_authorization_str_ref =
    REFTAG_TYPEDEF(siptag_proxy_authorization_str);
  tag_typedef_t _siptag_supported_str = SIPSTRTAG_TYPEDEF(supported);
  tag_typedef_t _siptag_supported_str_ref =
    REFTAG_TYPEDEF(siptag_supported_str);
  tag_typedef_t _siptag_request_disposition_str = SIPSTRTAG_TYPEDEF(request_disposition);
  tag_typedef_t _siptag_request_disposition_str_ref =
    REFTAG_TYPEDEF(siptag_request_disposition_str);
  tag_typedef_t _siptag_proxy_require = SIPHDRTAG_TYPEDEF(proxy_require);
  tag_typedef_t _siptag_proxy_require_ref =
    REFTAG_TYPEDEF(siptag_proxy_require);
  tag_typedef_t _siptag_authentication_info_str = SIPSTRTAG_TYPEDEF(authentication_info);
  tag_typedef_t _siptag_authentication_info_str_ref =
    REFTAG_TYPEDEF(siptag_authentication_info_str);
  tag_typedef_t _siptag_timestamp = SIPHDRTAG_TYPEDEF(timestamp);
  tag_typedef_t _siptag_timestamp_ref =
    REFTAG_TYPEDEF(siptag_timestamp);
  tag_typedef_t _siptag_payload_str = SIPSTRTAG_TYPEDEF(payload);
  tag_typedef_t _siptag_payload_str_ref =
    REFTAG_TYPEDEF(siptag_payload_str);
  tag_typedef_t _siptag_call_id_str = SIPSTRTAG_TYPEDEF(call_id);
  tag_typedef_t _siptag_call_id_str_ref =
    REFTAG_TYPEDEF(siptag_call_id_str);
  tag_typedef_t _siptag_status = SIPHDRTAG_TYPEDEF(status);
  tag_typedef_t _siptag_status_ref =
    REFTAG_TYPEDEF(siptag_status);
  tag_typedef_t _siptag_require_str = SIPSTRTAG_TYPEDEF(require);
  tag_typedef_t _siptag_require_str_ref =
    REFTAG_TYPEDEF(siptag_require_str);
  tag_typedef_t _siptag_min_expires = SIPHDRTAG_TYPEDEF(min_expires);
  tag_typedef_t _siptag_min_expires_ref =
    REFTAG_TYPEDEF(siptag_min_expires);
  tag_typedef_t _siptag_via_str = SIPSTRTAG_TYPEDEF(via);
  tag_typedef_t _siptag_via_str_ref =
    REFTAG_TYPEDEF(siptag_via_str);
  tag_typedef_t _siptag_separator = SIPHDRTAG_TYPEDEF(separator);
  tag_typedef_t _siptag_separator_ref =
    REFTAG_TYPEDEF(siptag_separator);
  tag_typedef_t _siptag_min_se_str = SIPSTRTAG_TYPEDEF(min_se);
  tag_typedef_t _siptag_min_se_str_ref =
    REFTAG_TYPEDEF(siptag_min_se_str);
  tag_typedef_t _siptag_contact = SIPHDRTAG_TYPEDEF(contact);
  tag_typedef_t _siptag_contact_ref =
    REFTAG_TYPEDEF(siptag_contact);
  tag_typedef_t _siptag_if_match_str = SIPSTRTAG_TYPEDEF(if_match);
  tag_typedef_t _siptag_if_match_str_ref =
    REFTAG_TYPEDEF(siptag_if_match_str);
  tag_typedef_t _siptag_referred_by = SIPHDRTAG_TYPEDEF(referred_by);
  tag_typedef_t _siptag_referred_by_ref =
    REFTAG_TYPEDEF(siptag_referred_by);
  tag_typedef_t _siptag_warning_str = SIPSTRTAG_TYPEDEF(warning);
  tag_typedef_t _siptag_warning_str_ref =
    REFTAG_TYPEDEF(siptag_warning_str);
  tag_typedef_t _siptag_route_str = SIPSTRTAG_TYPEDEF(route);
  tag_typedef_t _siptag_route_str_ref =
    REFTAG_TYPEDEF(siptag_route_str);
  tag_typedef_t _siptag_suppress_notify_if_match = SIPHDRTAG_TYPEDEF(suppress_notify_if_match);
  tag_typedef_t _siptag_suppress_notify_if_match_ref =
    REFTAG_TYPEDEF(siptag_suppress_notify_if_match);
  tag_typedef_t _siptag_content_language = SIPHDRTAG_TYPEDEF(content_language);
  tag_typedef_t _siptag_content_language_ref =
    REFTAG_TYPEDEF(siptag_content_language);
  tag_typedef_t _siptag_content_encoding = SIPHDRTAG_TYPEDEF(content_encoding);
  tag_typedef_t _siptag_content_encoding_ref =
    REFTAG_TYPEDEF(siptag_content_encoding);
  tag_typedef_t _siptag_authorization_str = SIPSTRTAG_TYPEDEF(authorization);
  tag_typedef_t _siptag_authorization_str_ref =
    REFTAG_TYPEDEF(siptag_authorization_str);
  tag_typedef_t _siptag_require = SIPHDRTAG_TYPEDEF(require);
  tag_typedef_t _siptag_require_ref =
    REFTAG_TYPEDEF(siptag_require);
  tag_typedef_t _siptag_date_str = SIPSTRTAG_TYPEDEF(date);
  tag_typedef_t _siptag_date_str_ref =
    REFTAG_TYPEDEF(siptag_date_str);
  tag_typedef_t _siptag_date = SIPHDRTAG_TYPEDEF(date);
  tag_typedef_t _siptag_date_ref =
    REFTAG_TYPEDEF(siptag_date);
  tag_typedef_t _siptag_mime_version_str = SIPSTRTAG_TYPEDEF(mime_version);
  tag_typedef_t _siptag_mime_version_str_ref =
    REFTAG_TYPEDEF(siptag_mime_version_str);
  tag_typedef_t _siptag_allow = SIPHDRTAG_TYPEDEF(allow);
  tag_typedef_t _siptag_allow_ref =
    REFTAG_TYPEDEF(siptag_allow);
  tag_typedef_t _siptag_accept_language = SIPHDRTAG_TYPEDEF(accept_language);
  tag_typedef_t _siptag_accept_language_ref =
    REFTAG_TYPEDEF(siptag_accept_language);
  tag_typedef_t _siptag_accept_encoding = SIPHDRTAG_TYPEDEF(accept_encoding);
  tag_typedef_t _siptag_accept_encoding_ref =
    REFTAG_TYPEDEF(siptag_accept_encoding);
  tag_typedef_t _siptag_organization_str = SIPSTRTAG_TYPEDEF(organization);
  tag_typedef_t _siptag_organization_str_ref =
    REFTAG_TYPEDEF(siptag_organization_str);
  tag_typedef_t _siptag_expires = SIPHDRTAG_TYPEDEF(expires);
  tag_typedef_t _siptag_expires_ref =
    REFTAG_TYPEDEF(siptag_expires);
  tag_typedef_t _siptag_suppress_body_if_match = SIPHDRTAG_TYPEDEF(suppress_body_if_match);
  tag_typedef_t _siptag_suppress_body_if_match_ref =
    REFTAG_TYPEDEF(siptag_suppress_body_if_match);
  tag_typedef_t _siptag_etag_str = SIPSTRTAG_TYPEDEF(etag);
  tag_typedef_t _siptag_etag_str_ref =
    REFTAG_TYPEDEF(siptag_etag_str);
  tag_typedef_t _siptag_privacy = SIPHDRTAG_TYPEDEF(privacy);
  tag_typedef_t _siptag_privacy_ref =
    REFTAG_TYPEDEF(siptag_privacy);
  tag_typedef_t _siptag_security_server_str = SIPSTRTAG_TYPEDEF(security_server);
  tag_typedef_t _siptag_security_server_str_ref =
    REFTAG_TYPEDEF(siptag_security_server_str);
  tag_typedef_t _siptag_service_route = SIPHDRTAG_TYPEDEF(service_route);
  tag_typedef_t _siptag_service_route_ref =
    REFTAG_TYPEDEF(siptag_service_route);
  tag_typedef_t _siptag_path_str = SIPSTRTAG_TYPEDEF(path);
  tag_typedef_t _siptag_path_str_ref =
    REFTAG_TYPEDEF(siptag_path_str);
  tag_typedef_t _siptag_session_expires_str = SIPSTRTAG_TYPEDEF(session_expires);
  tag_typedef_t _siptag_session_expires_str_ref =
    REFTAG_TYPEDEF(siptag_session_expires_str);
  tag_typedef_t _siptag_in_reply_to_str = SIPSTRTAG_TYPEDEF(in_reply_to);
  tag_typedef_t _siptag_in_reply_to_str_ref =
    REFTAG_TYPEDEF(siptag_in_reply_to_str);
  tag_typedef_t _siptag_p_preferred_identity_str = SIPSTRTAG_TYPEDEF(p_preferred_identity);
  tag_typedef_t _siptag_p_preferred_identity_str_ref =
    REFTAG_TYPEDEF(siptag_p_preferred_identity_str);
  tag_typedef_t _siptag_alert_info_str = SIPSTRTAG_TYPEDEF(alert_info);
  tag_typedef_t _siptag_alert_info_str_ref =
    REFTAG_TYPEDEF(siptag_alert_info_str);
  tag_typedef_t _siptag_security_client_str = SIPSTRTAG_TYPEDEF(security_client);
  tag_typedef_t _siptag_security_client_str_ref =
    REFTAG_TYPEDEF(siptag_security_client_str);
  tag_typedef_t _siptag_error_info_str = SIPSTRTAG_TYPEDEF(error_info);
  tag_typedef_t _siptag_error_info_str_ref =
    REFTAG_TYPEDEF(siptag_error_info_str);
  tag_typedef_t _siptag_user_agent = SIPHDRTAG_TYPEDEF(user_agent);
  tag_typedef_t _siptag_user_agent_ref =
    REFTAG_TYPEDEF(siptag_user_agent);
  tag_typedef_t _siptag_record_route = SIPHDRTAG_TYPEDEF(record_route);
  tag_typedef_t _siptag_record_route_ref =
    REFTAG_TYPEDEF(siptag_record_route);
  tag_typedef_t _siptag_p_asserted_identity_str = SIPSTRTAG_TYPEDEF(p_asserted_identity);
  tag_typedef_t _siptag_p_asserted_identity_str_ref =
    REFTAG_TYPEDEF(siptag_p_asserted_identity_str);
  tag_typedef_t _siptag_call_info_str = SIPSTRTAG_TYPEDEF(call_info);
  tag_typedef_t _siptag_call_info_str_ref =
    REFTAG_TYPEDEF(siptag_call_info_str);
  tag_typedef_t _siptag_reject_contact_str = SIPSTRTAG_TYPEDEF(reject_contact);
  tag_typedef_t _siptag_reject_contact_str_ref =
    REFTAG_TYPEDEF(siptag_reject_contact_str);
  tag_typedef_t _siptag_accept_contact_str = SIPSTRTAG_TYPEDEF(accept_contact);
  tag_typedef_t _siptag_accept_contact_str_ref =
    REFTAG_TYPEDEF(siptag_accept_contact_str);
  tag_typedef_t _siptag_unknown_str = SIPSTRTAG_TYPEDEF(unknown);
  tag_typedef_t _siptag_unknown_str_ref =
    REFTAG_TYPEDEF(siptag_unknown_str);
  tag_typedef_t _siptag_reply_to_str = SIPSTRTAG_TYPEDEF(reply_to);
  tag_typedef_t _siptag_reply_to_str_ref =
    REFTAG_TYPEDEF(siptag_reply_to_str);
  tag_typedef_t _siptag_refer_to_str = SIPSTRTAG_TYPEDEF(refer_to);
  tag_typedef_t _siptag_refer_to_str_ref =
    REFTAG_TYPEDEF(siptag_refer_to_str);
  tag_typedef_t _siptag_allow_events_str = SIPSTRTAG_TYPEDEF(allow_events);
  tag_typedef_t _siptag_allow_events_str_ref =
    REFTAG_TYPEDEF(siptag_allow_events_str);
  tag_typedef_t _siptag_timestamp_str = SIPSTRTAG_TYPEDEF(timestamp);
  tag_typedef_t _siptag_timestamp_str_ref =
    REFTAG_TYPEDEF(siptag_timestamp_str);
  tag_typedef_t _siptag_retry_after_str = SIPSTRTAG_TYPEDEF(retry_after);
  tag_typedef_t _siptag_retry_after_str_ref =
    REFTAG_TYPEDEF(siptag_retry_after_str);
  tag_typedef_t _siptag_rack_str = SIPSTRTAG_TYPEDEF(rack);
  tag_typedef_t _siptag_rack_str_ref =
    REFTAG_TYPEDEF(siptag_rack_str);
  tag_typedef_t _siptag_max_forwards_str = SIPSTRTAG_TYPEDEF(max_forwards);
  tag_typedef_t _siptag_max_forwards_str_ref =
    REFTAG_TYPEDEF(siptag_max_forwards_str);
  tag_typedef_t _siptag_reason_str = SIPSTRTAG_TYPEDEF(reason);
  tag_typedef_t _siptag_reason_str_ref =
    REFTAG_TYPEDEF(siptag_reason_str);
  tag_typedef_t _siptag_min_expires_str = SIPSTRTAG_TYPEDEF(min_expires);
  tag_typedef_t _siptag_min_expires_str_ref =
    REFTAG_TYPEDEF(siptag_min_expires_str);
  tag_typedef_t _siptag_separator_str = SIPSTRTAG_TYPEDEF(separator);
  tag_typedef_t _siptag_separator_str_ref =
    REFTAG_TYPEDEF(siptag_separator_str);
  tag_typedef_t _siptag_unsupported = SIPHDRTAG_TYPEDEF(unsupported);
  tag_typedef_t _siptag_unsupported_ref =
    REFTAG_TYPEDEF(siptag_unsupported);
  tag_typedef_t _siptag_from_str = SIPSTRTAG_TYPEDEF(from);
  tag_typedef_t _siptag_from_str_ref =
    REFTAG_TYPEDEF(siptag_from_str);
  tag_typedef_t _siptag_security_verify_str = SIPSTRTAG_TYPEDEF(security_verify);
  tag_typedef_t _siptag_security_verify_str_ref =
    REFTAG_TYPEDEF(siptag_security_verify_str);
  tag_typedef_t _siptag_user_agent_str = SIPSTRTAG_TYPEDEF(user_agent);
  tag_typedef_t _siptag_user_agent_str_ref =
    REFTAG_TYPEDEF(siptag_user_agent_str);
  tag_typedef_t _siptag_replaces_str = SIPSTRTAG_TYPEDEF(replaces);
  tag_typedef_t _siptag_replaces_str_ref =
    REFTAG_TYPEDEF(siptag_replaces_str);
  tag_typedef_t _siptag_supported = SIPHDRTAG_TYPEDEF(supported);
  tag_typedef_t _siptag_supported_ref =
    REFTAG_TYPEDEF(siptag_supported);
  tag_typedef_t _siptag_to = SIPHDRTAG_TYPEDEF(to);
  tag_typedef_t _siptag_to_ref =
    REFTAG_TYPEDEF(siptag_to);
  tag_typedef_t _siptag_server_str = SIPSTRTAG_TYPEDEF(server);
  tag_typedef_t _siptag_server_str_ref =
    REFTAG_TYPEDEF(siptag_server_str);
  tag_typedef_t _siptag_expires_str = SIPSTRTAG_TYPEDEF(expires);
  tag_typedef_t _siptag_expires_str_ref =
    REFTAG_TYPEDEF(siptag_expires_str);
  tag_typedef_t _siptag_route = SIPHDRTAG_TYPEDEF(route);
  tag_typedef_t _siptag_route_ref =
    REFTAG_TYPEDEF(siptag_route);
  tag_typedef_t _siptag_header_str = STRTAG_TYPEDEF(header_str);
  tag_typedef_t _siptag_header_str_ref =
    REFTAG_TYPEDEF(siptag_header_str);
  tag_typedef_t _siptag_error_str = SIPSTRTAG_TYPEDEF(error);
  tag_typedef_t _siptag_error_str_ref =
    REFTAG_TYPEDEF(siptag_error_str);
  tag_typedef_t _siptag_subject_str = SIPSTRTAG_TYPEDEF(subject);
  tag_typedef_t _siptag_subject_str_ref =
    REFTAG_TYPEDEF(siptag_subject_str);
  tag_typedef_t _siptag_rseq_str = SIPSTRTAG_TYPEDEF(rseq);
  tag_typedef_t _siptag_rseq_str_ref =
    REFTAG_TYPEDEF(siptag_rseq_str);
  tag_typedef_t _siptag_contact_str = SIPSTRTAG_TYPEDEF(contact);
  tag_typedef_t _siptag_contact_str_ref =
    REFTAG_TYPEDEF(siptag_contact_str);
  tag_typedef_t _siptag_cseq_str = SIPSTRTAG_TYPEDEF(cseq);
  tag_typedef_t _siptag_cseq_str_ref =
    REFTAG_TYPEDEF(siptag_cseq_str);
  tag_typedef_t _siptag_to_str = SIPSTRTAG_TYPEDEF(to);
  tag_typedef_t _siptag_to_str_ref =
    REFTAG_TYPEDEF(siptag_to_str);
  tag_typedef_t _siptag_max_forwards = SIPHDRTAG_TYPEDEF(max_forwards);
  tag_typedef_t _siptag_max_forwards_ref =
    REFTAG_TYPEDEF(siptag_max_forwards);
  tag_typedef_t _siptag_status_str = SIPSTRTAG_TYPEDEF(status);
  tag_typedef_t _siptag_status_str_ref =
    REFTAG_TYPEDEF(siptag_status_str);
  tag_typedef_t _siptag_request_str = SIPSTRTAG_TYPEDEF(request);
  tag_typedef_t _siptag_request_str_ref =
    REFTAG_TYPEDEF(siptag_request_str);
  tag_typedef_t _siptag_referred_by_str = SIPSTRTAG_TYPEDEF(referred_by);
  tag_typedef_t _siptag_referred_by_str_ref =
    REFTAG_TYPEDEF(siptag_referred_by_str);
  tag_typedef_t _siptag_accept_str = SIPSTRTAG_TYPEDEF(accept);
  tag_typedef_t _siptag_accept_str_ref =
    REFTAG_TYPEDEF(siptag_accept_str);
  tag_typedef_t _siptag_event_str = SIPSTRTAG_TYPEDEF(event);
  tag_typedef_t _siptag_event_str_ref =
    REFTAG_TYPEDEF(siptag_event_str);
  tag_typedef_t _siptag_header = {{ "sip", "header", siphdrtag_class, 0 }};
  tag_typedef_t _siptag_header_ref =
    REFTAG_TYPEDEF(siptag_header);
  tag_typedef_t _siptag_security_verify = SIPHDRTAG_TYPEDEF(security_verify);
  tag_typedef_t _siptag_security_verify_ref =
    REFTAG_TYPEDEF(siptag_security_verify);
  tag_typedef_t _siptag_if_match = SIPHDRTAG_TYPEDEF(if_match);
  tag_typedef_t _siptag_if_match_ref =
    REFTAG_TYPEDEF(siptag_if_match);
  tag_typedef_t _siptag_priority_str = SIPSTRTAG_TYPEDEF(priority);
  tag_typedef_t _siptag_priority_str_ref =
    REFTAG_TYPEDEF(siptag_priority_str);
  tag_typedef_t _siptag_call_id = SIPHDRTAG_TYPEDEF(call_id);
  tag_typedef_t _siptag_call_id_ref =
    REFTAG_TYPEDEF(siptag_call_id);
  tag_typedef_t _siptag_privacy_str = SIPSTRTAG_TYPEDEF(privacy);
  tag_typedef_t _siptag_privacy_str_ref =
    REFTAG_TYPEDEF(siptag_privacy_str);
  tag_typedef_t _siptag_path = SIPHDRTAG_TYPEDEF(path);
  tag_typedef_t _siptag_path_ref =
    REFTAG_TYPEDEF(siptag_path);
  tag_typedef_t _siptag_min_se = SIPHDRTAG_TYPEDEF(min_se);
  tag_typedef_t _siptag_min_se_ref =
    REFTAG_TYPEDEF(siptag_min_se);
  tag_typedef_t _siptag_allow_str = SIPSTRTAG_TYPEDEF(allow);
  tag_typedef_t _siptag_allow_str_ref =
    REFTAG_TYPEDEF(siptag_allow_str);
  tag_typedef_t _siptag_in_reply_to = SIPHDRTAG_TYPEDEF(in_reply_to);
  tag_typedef_t _siptag_in_reply_to_ref =
    REFTAG_TYPEDEF(siptag_in_reply_to);
  tag_typedef_t _siptag_warning = SIPHDRTAG_TYPEDEF(warning);
  tag_typedef_t _siptag_warning_ref =
    REFTAG_TYPEDEF(siptag_warning);
  tag_typedef_t _siptag_priority = SIPHDRTAG_TYPEDEF(priority);
  tag_typedef_t _siptag_priority_ref =
    REFTAG_TYPEDEF(siptag_priority);
  tag_typedef_t _siptag_p_preferred_identity = SIPHDRTAG_TYPEDEF(p_preferred_identity);
  tag_typedef_t _siptag_p_preferred_identity_ref =
    REFTAG_TYPEDEF(siptag_p_preferred_identity);
  tag_typedef_t _siptag_rseq = SIPHDRTAG_TYPEDEF(rseq);
  tag_typedef_t _siptag_rseq_ref =
    REFTAG_TYPEDEF(siptag_rseq);
  tag_typedef_t _siptag_p_asserted_identity = SIPHDRTAG_TYPEDEF(p_asserted_identity);
  tag_typedef_t _siptag_p_asserted_identity_ref =
    REFTAG_TYPEDEF(siptag_p_asserted_identity);
  tag_typedef_t _siptag_reply_to = SIPHDRTAG_TYPEDEF(reply_to);
  tag_typedef_t _siptag_reply_to_ref =
    REFTAG_TYPEDEF(siptag_reply_to);
  tag_typedef_t _siptag_content_type = SIPHDRTAG_TYPEDEF(content_type);
  tag_typedef_t _siptag_content_type_ref =
    REFTAG_TYPEDEF(siptag_content_type);
  tag_typedef_t _siptag_payload = SIPHDRTAG_TYPEDEF(payload);
  tag_typedef_t _siptag_payload_ref =
    REFTAG_TYPEDEF(siptag_payload);
  tag_typedef_t _siptag_sip = SIPMSGTAG_TYPEDEF(sip);
  tag_typedef_t _siptag_sip_ref =
    REFTAG_TYPEDEF(siptag_sip);
  tag_typedef_t _siptag_proxy_authorization = SIPHDRTAG_TYPEDEF(proxy_authorization);
  tag_typedef_t _siptag_proxy_authorization_ref =
    REFTAG_TYPEDEF(siptag_proxy_authorization);
  tag_typedef_t _siptag_security_client = SIPHDRTAG_TYPEDEF(security_client);
  tag_typedef_t _siptag_security_client_ref =
    REFTAG_TYPEDEF(siptag_security_client);
  tag_typedef_t _siptag_retry_after = SIPHDRTAG_TYPEDEF(retry_after);
  tag_typedef_t _siptag_retry_after_ref =
    REFTAG_TYPEDEF(siptag_retry_after);
  tag_typedef_t _siptag_reason = SIPHDRTAG_TYPEDEF(reason);
  tag_typedef_t _siptag_reason_ref =
    REFTAG_TYPEDEF(siptag_reason);
  tag_typedef_t _siptag_from = SIPHDRTAG_TYPEDEF(from);
  tag_typedef_t _siptag_from_ref =
    REFTAG_TYPEDEF(siptag_from);
  tag_typedef_t _siptag_refer_sub = SIPHDRTAG_TYPEDEF(refer_sub);
  tag_typedef_t _siptag_refer_sub_ref =
    REFTAG_TYPEDEF(siptag_refer_sub);
  tag_typedef_t _siptag_allow_events = SIPHDRTAG_TYPEDEF(allow_events);
  tag_typedef_t _siptag_allow_events_ref =
    REFTAG_TYPEDEF(siptag_allow_events);
  tag_typedef_t _siptag_refer_to = SIPHDRTAG_TYPEDEF(refer_to);
  tag_typedef_t _siptag_refer_to_ref =
    REFTAG_TYPEDEF(siptag_refer_to);
  tag_typedef_t _siptag_via = SIPHDRTAG_TYPEDEF(via);
  tag_typedef_t _siptag_via_ref =
    REFTAG_TYPEDEF(siptag_via);
  tag_typedef_t _siptag_authorization = SIPHDRTAG_TYPEDEF(authorization);
  tag_typedef_t _siptag_authorization_ref =
    REFTAG_TYPEDEF(siptag_authorization);
  tag_typedef_t _siptag_organization = SIPHDRTAG_TYPEDEF(organization);
  tag_typedef_t _siptag_organization_ref =
    REFTAG_TYPEDEF(siptag_organization);
  tag_typedef_t _siptag_content_disposition = SIPHDRTAG_TYPEDEF(content_disposition);
  tag_typedef_t _siptag_content_disposition_ref =
    REFTAG_TYPEDEF(siptag_content_disposition);
  tag_typedef_t _siptag_request_disposition = SIPHDRTAG_TYPEDEF(request_disposition);
  tag_typedef_t _siptag_request_disposition_ref =
    REFTAG_TYPEDEF(siptag_request_disposition);
  tag_typedef_t _siptag_etag = SIPHDRTAG_TYPEDEF(etag);
  tag_typedef_t _siptag_etag_ref =
    REFTAG_TYPEDEF(siptag_etag);
  tag_typedef_t _siptag_proxy_authentication_info = SIPHDRTAG_TYPEDEF(proxy_authentication_info);
  tag_typedef_t _siptag_proxy_authentication_info_ref =
    REFTAG_TYPEDEF(siptag_proxy_authentication_info);

  *(struct tag_type_s *)siptag_subject = *_siptag_subject;
  *(struct tag_type_s *)siptag_subject_ref = *_siptag_subject_ref;
  *(struct tag_type_s *)siptag_mime_version = *_siptag_mime_version;
  *(struct tag_type_s *)siptag_mime_version_ref = *_siptag_mime_version_ref;
  *(struct tag_type_s *)siptag_cseq = *_siptag_cseq;
  *(struct tag_type_s *)siptag_cseq_ref = *_siptag_cseq_ref;
  *(struct tag_type_s *)siptag_security_server = *_siptag_security_server;
  *(struct tag_type_s *)siptag_security_server_ref = *_siptag_security_server_ref;
  *(struct tag_type_s *)siptag_authentication_info = *_siptag_authentication_info;
  *(struct tag_type_s *)siptag_authentication_info_ref = *_siptag_authentication_info_ref;
  *(struct tag_type_s *)siptag_remote_party_id = *_siptag_remote_party_id;
  *(struct tag_type_s *)siptag_remote_party_id_ref = *_siptag_remote_party_id_ref;
  *(struct tag_type_s *)siptag_accept = *_siptag_accept;
  *(struct tag_type_s *)siptag_accept_ref = *_siptag_accept_ref;
  *(struct tag_type_s *)siptag_rack = *_siptag_rack;
  *(struct tag_type_s *)siptag_rack_ref = *_siptag_rack_ref;
  *(struct tag_type_s *)siptag_error = *_siptag_error;
  *(struct tag_type_s *)siptag_error_ref = *_siptag_error_ref;
  *(struct tag_type_s *)siptag_suppress_notify_if_match_str = *_siptag_suppress_notify_if_match_str;
  *(struct tag_type_s *)siptag_suppress_notify_if_match_str_ref = *_siptag_suppress_notify_if_match_str_ref;
  *(struct tag_type_s *)siptag_any = *_siptag_any;
  *(struct tag_type_s *)siptag_any_ref = *_siptag_any_ref;
  *(struct tag_type_s *)siptag_suppress_body_if_match_str = *_siptag_suppress_body_if_match_str;
  *(struct tag_type_s *)siptag_suppress_body_if_match_str_ref = *_siptag_suppress_body_if_match_str_ref;
  *(struct tag_type_s *)siptag_subscription_state_str = *_siptag_subscription_state_str;
  *(struct tag_type_s *)siptag_subscription_state_str_ref = *_siptag_subscription_state_str_ref;
  *(struct tag_type_s *)siptag_proxy_authenticate_str = *_siptag_proxy_authenticate_str;
  *(struct tag_type_s *)siptag_proxy_authenticate_str_ref = *_siptag_proxy_authenticate_str_ref;
  *(struct tag_type_s *)siptag_server = *_siptag_server;
  *(struct tag_type_s *)siptag_server_ref = *_siptag_server_ref;
  *(struct tag_type_s *)siptag_replaces = *_siptag_replaces;
  *(struct tag_type_s *)siptag_replaces_ref = *_siptag_replaces_ref;
  *(struct tag_type_s *)siptag_request = *_siptag_request;
  *(struct tag_type_s *)siptag_request_ref = *_siptag_request_ref;
  *(struct tag_type_s *)siptag_www_authenticate_str = *_siptag_www_authenticate_str;
  *(struct tag_type_s *)siptag_www_authenticate_str_ref = *_siptag_www_authenticate_str_ref;
  *(struct tag_type_s *)siptag_error_info = *_siptag_error_info;
  *(struct tag_type_s *)siptag_error_info_ref = *_siptag_error_info_ref;
  *(struct tag_type_s *)siptag_content_language_str = *_siptag_content_language_str;
  *(struct tag_type_s *)siptag_content_language_str_ref = *_siptag_content_language_str_ref;
  *(struct tag_type_s *)siptag_alert_info = *_siptag_alert_info;
  *(struct tag_type_s *)siptag_alert_info_ref = *_siptag_alert_info_ref;
  *(struct tag_type_s *)siptag_remote_party_id_str = *_siptag_remote_party_id_str;
  *(struct tag_type_s *)siptag_remote_party_id_str_ref = *_siptag_remote_party_id_str_ref;
  *(struct tag_type_s *)siptag_call_info = *_siptag_call_info;
  *(struct tag_type_s *)siptag_call_info_ref = *_siptag_call_info_ref;
  *(struct tag_type_s *)siptag_accept_language_str = *_siptag_accept_language_str;
  *(struct tag_type_s *)siptag_accept_language_str_ref = *_siptag_accept_language_str_ref;
  *(struct tag_type_s *)siptag_proxy_authenticate = *_siptag_proxy_authenticate;
  *(struct tag_type_s *)siptag_proxy_authenticate_ref = *_siptag_proxy_authenticate_ref;
  *(struct tag_type_s *)siptag_proxy_authentication_info_str = *_siptag_proxy_authentication_info_str;
  *(struct tag_type_s *)siptag_proxy_authentication_info_str_ref = *_siptag_proxy_authentication_info_str_ref;
  *(struct tag_type_s *)siptag_unknown = *_siptag_unknown;
  *(struct tag_type_s *)siptag_unknown_ref = *_siptag_unknown_ref;
  *(struct tag_type_s *)siptag_event = *_siptag_event;
  *(struct tag_type_s *)siptag_event_ref = *_siptag_event_ref;
  *(struct tag_type_s *)siptag_subscription_state = *_siptag_subscription_state;
  *(struct tag_type_s *)siptag_subscription_state_ref = *_siptag_subscription_state_ref;
  *(struct tag_type_s *)siptag_content_encoding_str = *_siptag_content_encoding_str;
  *(struct tag_type_s *)siptag_content_encoding_str_ref = *_siptag_content_encoding_str_ref;
  *(struct tag_type_s *)siptag_end = *_siptag_end;
  *(struct tag_type_s *)siptag_end_ref = *_siptag_end_ref;
  *(struct tag_type_s *)siptag_proxy_require_str = *_siptag_proxy_require_str;
  *(struct tag_type_s *)siptag_proxy_require_str_ref = *_siptag_proxy_require_str_ref;
  *(struct tag_type_s *)siptag_accept_contact = *_siptag_accept_contact;
  *(struct tag_type_s *)siptag_accept_contact_ref = *_siptag_accept_contact_ref;
  *(struct tag_type_s *)siptag_reject_contact = *_siptag_reject_contact;
  *(struct tag_type_s *)siptag_reject_contact_ref = *_siptag_reject_contact_ref;
  *(struct tag_type_s *)siptag_accept_encoding_str = *_siptag_accept_encoding_str;
  *(struct tag_type_s *)siptag_accept_encoding_str_ref = *_siptag_accept_encoding_str_ref;
  *(struct tag_type_s *)siptag_www_authenticate = *_siptag_www_authenticate;
  *(struct tag_type_s *)siptag_www_authenticate_ref = *_siptag_www_authenticate_ref;
  *(struct tag_type_s *)siptag_service_route_str = *_siptag_service_route_str;
  *(struct tag_type_s *)siptag_service_route_str_ref = *_siptag_service_route_str_ref;
  *(struct tag_type_s *)siptag_record_route_str = *_siptag_record_route_str;
  *(struct tag_type_s *)siptag_record_route_str_ref = *_siptag_record_route_str_ref;
  *(struct tag_type_s *)siptag_unsupported_str = *_siptag_unsupported_str;
  *(struct tag_type_s *)siptag_unsupported_str_ref = *_siptag_unsupported_str_ref;
  *(struct tag_type_s *)siptag_content_type_str = *_siptag_content_type_str;
  *(struct tag_type_s *)siptag_content_type_str_ref = *_siptag_content_type_str_ref;
  *(struct tag_type_s *)siptag_refer_sub_str = *_siptag_refer_sub_str;
  *(struct tag_type_s *)siptag_refer_sub_str_ref = *_siptag_refer_sub_str_ref;
  *(struct tag_type_s *)siptag_session_expires = *_siptag_session_expires;
  *(struct tag_type_s *)siptag_session_expires_ref = *_siptag_session_expires_ref;
  *(struct tag_type_s *)siptag_content_length = *_siptag_content_length;
  *(struct tag_type_s *)siptag_content_length_ref = *_siptag_content_length_ref;
  *(struct tag_type_s *)siptag_content_length_str = *_siptag_content_length_str;
  *(struct tag_type_s *)siptag_content_length_str_ref = *_siptag_content_length_str_ref;
  *(struct tag_type_s *)siptag_proxy_require = *_siptag_proxy_require;
  *(struct tag_type_s *)siptag_proxy_require_ref = *_siptag_proxy_require_ref;
  *(struct tag_type_s *)siptag_request_disposition_str = *_siptag_request_disposition_str;
  *(struct tag_type_s *)siptag_request_disposition_str_ref = *_siptag_request_disposition_str_ref;
  *(struct tag_type_s *)siptag_supported_str = *_siptag_supported_str;
  *(struct tag_type_s *)siptag_supported_str_ref = *_siptag_supported_str_ref;
  *(struct tag_type_s *)siptag_proxy_authorization_str = *_siptag_proxy_authorization_str;
  *(struct tag_type_s *)siptag_proxy_authorization_str_ref = *_siptag_proxy_authorization_str_ref;
  *(struct tag_type_s *)siptag_content_disposition_str = *_siptag_content_disposition_str;
  *(struct tag_type_s *)siptag_content_disposition_str_ref = *_siptag_content_disposition_str_ref;
  *(struct tag_type_s *)siptag_timestamp = *_siptag_timestamp;
  *(struct tag_type_s *)siptag_timestamp_ref = *_siptag_timestamp_ref;
  *(struct tag_type_s *)siptag_authentication_info_str = *_siptag_authentication_info_str;
  *(struct tag_type_s *)siptag_authentication_info_str_ref = *_siptag_authentication_info_str_ref;
  *(struct tag_type_s *)siptag_status = *_siptag_status;
  *(struct tag_type_s *)siptag_status_ref = *_siptag_status_ref;
  *(struct tag_type_s *)siptag_call_id_str = *_siptag_call_id_str;
  *(struct tag_type_s *)siptag_call_id_str_ref = *_siptag_call_id_str_ref;
  *(struct tag_type_s *)siptag_payload_str = *_siptag_payload_str;
  *(struct tag_type_s *)siptag_payload_str_ref = *_siptag_payload_str_ref;
  *(struct tag_type_s *)siptag_via_str = *_siptag_via_str;
  *(struct tag_type_s *)siptag_via_str_ref = *_siptag_via_str_ref;
  *(struct tag_type_s *)siptag_min_expires = *_siptag_min_expires;
  *(struct tag_type_s *)siptag_min_expires_ref = *_siptag_min_expires_ref;
  *(struct tag_type_s *)siptag_require_str = *_siptag_require_str;
  *(struct tag_type_s *)siptag_require_str_ref = *_siptag_require_str_ref;
  *(struct tag_type_s *)siptag_contact = *_siptag_contact;
  *(struct tag_type_s *)siptag_contact_ref = *_siptag_contact_ref;
  *(struct tag_type_s *)siptag_min_se_str = *_siptag_min_se_str;
  *(struct tag_type_s *)siptag_min_se_str_ref = *_siptag_min_se_str_ref;
  *(struct tag_type_s *)siptag_separator = *_siptag_separator;
  *(struct tag_type_s *)siptag_separator_ref = *_siptag_separator_ref;
  *(struct tag_type_s *)siptag_route_str = *_siptag_route_str;
  *(struct tag_type_s *)siptag_route_str_ref = *_siptag_route_str_ref;
  *(struct tag_type_s *)siptag_warning_str = *_siptag_warning_str;
  *(struct tag_type_s *)siptag_warning_str_ref = *_siptag_warning_str_ref;
  *(struct tag_type_s *)siptag_referred_by = *_siptag_referred_by;
  *(struct tag_type_s *)siptag_referred_by_ref = *_siptag_referred_by_ref;
  *(struct tag_type_s *)siptag_if_match_str = *_siptag_if_match_str;
  *(struct tag_type_s *)siptag_if_match_str_ref = *_siptag_if_match_str_ref;
  *(struct tag_type_s *)siptag_date = *_siptag_date;
  *(struct tag_type_s *)siptag_date_ref = *_siptag_date_ref;
  *(struct tag_type_s *)siptag_date_str = *_siptag_date_str;
  *(struct tag_type_s *)siptag_date_str_ref = *_siptag_date_str_ref;
  *(struct tag_type_s *)siptag_require = *_siptag_require;
  *(struct tag_type_s *)siptag_require_ref = *_siptag_require_ref;
  *(struct tag_type_s *)siptag_authorization_str = *_siptag_authorization_str;
  *(struct tag_type_s *)siptag_authorization_str_ref = *_siptag_authorization_str_ref;
  *(struct tag_type_s *)siptag_content_encoding = *_siptag_content_encoding;
  *(struct tag_type_s *)siptag_content_encoding_ref = *_siptag_content_encoding_ref;
  *(struct tag_type_s *)siptag_content_language = *_siptag_content_language;
  *(struct tag_type_s *)siptag_content_language_ref = *_siptag_content_language_ref;
  *(struct tag_type_s *)siptag_suppress_notify_if_match = *_siptag_suppress_notify_if_match;
  *(struct tag_type_s *)siptag_suppress_notify_if_match_ref = *_siptag_suppress_notify_if_match_ref;
  *(struct tag_type_s *)siptag_expires = *_siptag_expires;
  *(struct tag_type_s *)siptag_expires_ref = *_siptag_expires_ref;
  *(struct tag_type_s *)siptag_organization_str = *_siptag_organization_str;
  *(struct tag_type_s *)siptag_organization_str_ref = *_siptag_organization_str_ref;
  *(struct tag_type_s *)siptag_accept_encoding = *_siptag_accept_encoding;
  *(struct tag_type_s *)siptag_accept_encoding_ref = *_siptag_accept_encoding_ref;
  *(struct tag_type_s *)siptag_accept_language = *_siptag_accept_language;
  *(struct tag_type_s *)siptag_accept_language_ref = *_siptag_accept_language_ref;
  *(struct tag_type_s *)siptag_allow = *_siptag_allow;
  *(struct tag_type_s *)siptag_allow_ref = *_siptag_allow_ref;
  *(struct tag_type_s *)siptag_mime_version_str = *_siptag_mime_version_str;
  *(struct tag_type_s *)siptag_mime_version_str_ref = *_siptag_mime_version_str_ref;
  *(struct tag_type_s *)siptag_security_server_str = *_siptag_security_server_str;
  *(struct tag_type_s *)siptag_security_server_str_ref = *_siptag_security_server_str_ref;
  *(struct tag_type_s *)siptag_privacy = *_siptag_privacy;
  *(struct tag_type_s *)siptag_privacy_ref = *_siptag_privacy_ref;
  *(struct tag_type_s *)siptag_etag_str = *_siptag_etag_str;
  *(struct tag_type_s *)siptag_etag_str_ref = *_siptag_etag_str_ref;
  *(struct tag_type_s *)siptag_suppress_body_if_match = *_siptag_suppress_body_if_match;
  *(struct tag_type_s *)siptag_suppress_body_if_match_ref = *_siptag_suppress_body_if_match_ref;
  *(struct tag_type_s *)siptag_in_reply_to_str = *_siptag_in_reply_to_str;
  *(struct tag_type_s *)siptag_in_reply_to_str_ref = *_siptag_in_reply_to_str_ref;
  *(struct tag_type_s *)siptag_session_expires_str = *_siptag_session_expires_str;
  *(struct tag_type_s *)siptag_session_expires_str_ref = *_siptag_session_expires_str_ref;
  *(struct tag_type_s *)siptag_path_str = *_siptag_path_str;
  *(struct tag_type_s *)siptag_path_str_ref = *_siptag_path_str_ref;
  *(struct tag_type_s *)siptag_service_route = *_siptag_service_route;
  *(struct tag_type_s *)siptag_service_route_ref = *_siptag_service_route_ref;
  *(struct tag_type_s *)siptag_record_route = *_siptag_record_route;
  *(struct tag_type_s *)siptag_record_route_ref = *_siptag_record_route_ref;
  *(struct tag_type_s *)siptag_user_agent = *_siptag_user_agent;
  *(struct tag_type_s *)siptag_user_agent_ref = *_siptag_user_agent_ref;
  *(struct tag_type_s *)siptag_error_info_str = *_siptag_error_info_str;
  *(struct tag_type_s *)siptag_error_info_str_ref = *_siptag_error_info_str_ref;
  *(struct tag_type_s *)siptag_security_client_str = *_siptag_security_client_str;
  *(struct tag_type_s *)siptag_security_client_str_ref = *_siptag_security_client_str_ref;
  *(struct tag_type_s *)siptag_alert_info_str = *_siptag_alert_info_str;
  *(struct tag_type_s *)siptag_alert_info_str_ref = *_siptag_alert_info_str_ref;
  *(struct tag_type_s *)siptag_p_preferred_identity_str = *_siptag_p_preferred_identity_str;
  *(struct tag_type_s *)siptag_p_preferred_identity_str_ref = *_siptag_p_preferred_identity_str_ref;
  *(struct tag_type_s *)siptag_accept_contact_str = *_siptag_accept_contact_str;
  *(struct tag_type_s *)siptag_accept_contact_str_ref = *_siptag_accept_contact_str_ref;
  *(struct tag_type_s *)siptag_reject_contact_str = *_siptag_reject_contact_str;
  *(struct tag_type_s *)siptag_reject_contact_str_ref = *_siptag_reject_contact_str_ref;
  *(struct tag_type_s *)siptag_call_info_str = *_siptag_call_info_str;
  *(struct tag_type_s *)siptag_call_info_str_ref = *_siptag_call_info_str_ref;
  *(struct tag_type_s *)siptag_p_asserted_identity_str = *_siptag_p_asserted_identity_str;
  *(struct tag_type_s *)siptag_p_asserted_identity_str_ref = *_siptag_p_asserted_identity_str_ref;
  *(struct tag_type_s *)siptag_max_forwards_str = *_siptag_max_forwards_str;
  *(struct tag_type_s *)siptag_max_forwards_str_ref = *_siptag_max_forwards_str_ref;
  *(struct tag_type_s *)siptag_rack_str = *_siptag_rack_str;
  *(struct tag_type_s *)siptag_rack_str_ref = *_siptag_rack_str_ref;
  *(struct tag_type_s *)siptag_retry_after_str = *_siptag_retry_after_str;
  *(struct tag_type_s *)siptag_retry_after_str_ref = *_siptag_retry_after_str_ref;
  *(struct tag_type_s *)siptag_timestamp_str = *_siptag_timestamp_str;
  *(struct tag_type_s *)siptag_timestamp_str_ref = *_siptag_timestamp_str_ref;
  *(struct tag_type_s *)siptag_allow_events_str = *_siptag_allow_events_str;
  *(struct tag_type_s *)siptag_allow_events_str_ref = *_siptag_allow_events_str_ref;
  *(struct tag_type_s *)siptag_refer_to_str = *_siptag_refer_to_str;
  *(struct tag_type_s *)siptag_refer_to_str_ref = *_siptag_refer_to_str_ref;
  *(struct tag_type_s *)siptag_reply_to_str = *_siptag_reply_to_str;
  *(struct tag_type_s *)siptag_reply_to_str_ref = *_siptag_reply_to_str_ref;
  *(struct tag_type_s *)siptag_unknown_str = *_siptag_unknown_str;
  *(struct tag_type_s *)siptag_unknown_str_ref = *_siptag_unknown_str_ref;
  *(struct tag_type_s *)siptag_min_expires_str = *_siptag_min_expires_str;
  *(struct tag_type_s *)siptag_min_expires_str_ref = *_siptag_min_expires_str_ref;
  *(struct tag_type_s *)siptag_reason_str = *_siptag_reason_str;
  *(struct tag_type_s *)siptag_reason_str_ref = *_siptag_reason_str_ref;
  *(struct tag_type_s *)siptag_from_str = *_siptag_from_str;
  *(struct tag_type_s *)siptag_from_str_ref = *_siptag_from_str_ref;
  *(struct tag_type_s *)siptag_unsupported = *_siptag_unsupported;
  *(struct tag_type_s *)siptag_unsupported_ref = *_siptag_unsupported_ref;
  *(struct tag_type_s *)siptag_separator_str = *_siptag_separator_str;
  *(struct tag_type_s *)siptag_separator_str_ref = *_siptag_separator_str_ref;
  *(struct tag_type_s *)siptag_user_agent_str = *_siptag_user_agent_str;
  *(struct tag_type_s *)siptag_user_agent_str_ref = *_siptag_user_agent_str_ref;
  *(struct tag_type_s *)siptag_security_verify_str = *_siptag_security_verify_str;
  *(struct tag_type_s *)siptag_security_verify_str_ref = *_siptag_security_verify_str_ref;
  *(struct tag_type_s *)siptag_to = *_siptag_to;
  *(struct tag_type_s *)siptag_to_ref = *_siptag_to_ref;
  *(struct tag_type_s *)siptag_supported = *_siptag_supported;
  *(struct tag_type_s *)siptag_supported_ref = *_siptag_supported_ref;
  *(struct tag_type_s *)siptag_replaces_str = *_siptag_replaces_str;
  *(struct tag_type_s *)siptag_replaces_str_ref = *_siptag_replaces_str_ref;
  *(struct tag_type_s *)siptag_header_str = *_siptag_header_str;
  *(struct tag_type_s *)siptag_header_str_ref = *_siptag_header_str_ref;
  *(struct tag_type_s *)siptag_route = *_siptag_route;
  *(struct tag_type_s *)siptag_route_ref = *_siptag_route_ref;
  *(struct tag_type_s *)siptag_expires_str = *_siptag_expires_str;
  *(struct tag_type_s *)siptag_expires_str_ref = *_siptag_expires_str_ref;
  *(struct tag_type_s *)siptag_server_str = *_siptag_server_str;
  *(struct tag_type_s *)siptag_server_str_ref = *_siptag_server_str_ref;
  *(struct tag_type_s *)siptag_request_str = *_siptag_request_str;
  *(struct tag_type_s *)siptag_request_str_ref = *_siptag_request_str_ref;
  *(struct tag_type_s *)siptag_status_str = *_siptag_status_str;
  *(struct tag_type_s *)siptag_status_str_ref = *_siptag_status_str_ref;
  *(struct tag_type_s *)siptag_max_forwards = *_siptag_max_forwards;
  *(struct tag_type_s *)siptag_max_forwards_ref = *_siptag_max_forwards_ref;
  *(struct tag_type_s *)siptag_to_str = *_siptag_to_str;
  *(struct tag_type_s *)siptag_to_str_ref = *_siptag_to_str_ref;
  *(struct tag_type_s *)siptag_cseq_str = *_siptag_cseq_str;
  *(struct tag_type_s *)siptag_cseq_str_ref = *_siptag_cseq_str_ref;
  *(struct tag_type_s *)siptag_contact_str = *_siptag_contact_str;
  *(struct tag_type_s *)siptag_contact_str_ref = *_siptag_contact_str_ref;
  *(struct tag_type_s *)siptag_rseq_str = *_siptag_rseq_str;
  *(struct tag_type_s *)siptag_rseq_str_ref = *_siptag_rseq_str_ref;
  *(struct tag_type_s *)siptag_subject_str = *_siptag_subject_str;
  *(struct tag_type_s *)siptag_subject_str_ref = *_siptag_subject_str_ref;
  *(struct tag_type_s *)siptag_error_str = *_siptag_error_str;
  *(struct tag_type_s *)siptag_error_str_ref = *_siptag_error_str_ref;
  *(struct tag_type_s *)siptag_accept_str = *_siptag_accept_str;
  *(struct tag_type_s *)siptag_accept_str_ref = *_siptag_accept_str_ref;
  *(struct tag_type_s *)siptag_referred_by_str = *_siptag_referred_by_str;
  *(struct tag_type_s *)siptag_referred_by_str_ref = *_siptag_referred_by_str_ref;
  *(struct tag_type_s *)siptag_header = *_siptag_header;
  *(struct tag_type_s *)siptag_header_ref = *_siptag_header_ref;
  *(struct tag_type_s *)siptag_event_str = *_siptag_event_str;
  *(struct tag_type_s *)siptag_event_str_ref = *_siptag_event_str_ref;
  *(struct tag_type_s *)siptag_security_verify = *_siptag_security_verify;
  *(struct tag_type_s *)siptag_security_verify_ref = *_siptag_security_verify_ref;
  *(struct tag_type_s *)siptag_call_id = *_siptag_call_id;
  *(struct tag_type_s *)siptag_call_id_ref = *_siptag_call_id_ref;
  *(struct tag_type_s *)siptag_priority_str = *_siptag_priority_str;
  *(struct tag_type_s *)siptag_priority_str_ref = *_siptag_priority_str_ref;
  *(struct tag_type_s *)siptag_if_match = *_siptag_if_match;
  *(struct tag_type_s *)siptag_if_match_ref = *_siptag_if_match_ref;
  *(struct tag_type_s *)siptag_in_reply_to = *_siptag_in_reply_to;
  *(struct tag_type_s *)siptag_in_reply_to_ref = *_siptag_in_reply_to_ref;
  *(struct tag_type_s *)siptag_allow_str = *_siptag_allow_str;
  *(struct tag_type_s *)siptag_allow_str_ref = *_siptag_allow_str_ref;
  *(struct tag_type_s *)siptag_min_se = *_siptag_min_se;
  *(struct tag_type_s *)siptag_min_se_ref = *_siptag_min_se_ref;
  *(struct tag_type_s *)siptag_path = *_siptag_path;
  *(struct tag_type_s *)siptag_path_ref = *_siptag_path_ref;
  *(struct tag_type_s *)siptag_privacy_str = *_siptag_privacy_str;
  *(struct tag_type_s *)siptag_privacy_str_ref = *_siptag_privacy_str_ref;
  *(struct tag_type_s *)siptag_priority = *_siptag_priority;
  *(struct tag_type_s *)siptag_priority_ref = *_siptag_priority_ref;
  *(struct tag_type_s *)siptag_warning = *_siptag_warning;
  *(struct tag_type_s *)siptag_warning_ref = *_siptag_warning_ref;
  *(struct tag_type_s *)siptag_rseq = *_siptag_rseq;
  *(struct tag_type_s *)siptag_rseq_ref = *_siptag_rseq_ref;
  *(struct tag_type_s *)siptag_p_preferred_identity = *_siptag_p_preferred_identity;
  *(struct tag_type_s *)siptag_p_preferred_identity_ref = *_siptag_p_preferred_identity_ref;
  *(struct tag_type_s *)siptag_content_type = *_siptag_content_type;
  *(struct tag_type_s *)siptag_content_type_ref = *_siptag_content_type_ref;
  *(struct tag_type_s *)siptag_reply_to = *_siptag_reply_to;
  *(struct tag_type_s *)siptag_reply_to_ref = *_siptag_reply_to_ref;
  *(struct tag_type_s *)siptag_p_asserted_identity = *_siptag_p_asserted_identity;
  *(struct tag_type_s *)siptag_p_asserted_identity_ref = *_siptag_p_asserted_identity_ref;
  *(struct tag_type_s *)siptag_payload = *_siptag_payload;
  *(struct tag_type_s *)siptag_payload_ref = *_siptag_payload_ref;
  *(struct tag_type_s *)siptag_sip = *_siptag_sip;
  *(struct tag_type_s *)siptag_sip_ref = *_siptag_sip_ref;
  *(struct tag_type_s *)siptag_proxy_authorization = *_siptag_proxy_authorization;
  *(struct tag_type_s *)siptag_proxy_authorization_ref = *_siptag_proxy_authorization_ref;
  *(struct tag_type_s *)siptag_retry_after = *_siptag_retry_after;
  *(struct tag_type_s *)siptag_retry_after_ref = *_siptag_retry_after_ref;
  *(struct tag_type_s *)siptag_security_client = *_siptag_security_client;
  *(struct tag_type_s *)siptag_security_client_ref = *_siptag_security_client_ref;
  *(struct tag_type_s *)siptag_reason = *_siptag_reason;
  *(struct tag_type_s *)siptag_reason_ref = *_siptag_reason_ref;
  *(struct tag_type_s *)siptag_from = *_siptag_from;
  *(struct tag_type_s *)siptag_from_ref = *_siptag_from_ref;
  *(struct tag_type_s *)siptag_allow_events = *_siptag_allow_events;
  *(struct tag_type_s *)siptag_allow_events_ref = *_siptag_allow_events_ref;
  *(struct tag_type_s *)siptag_refer_sub = *_siptag_refer_sub;
  *(struct tag_type_s *)siptag_refer_sub_ref = *_siptag_refer_sub_ref;
  *(struct tag_type_s *)siptag_via = *_siptag_via;
  *(struct tag_type_s *)siptag_via_ref = *_siptag_via_ref;
  *(struct tag_type_s *)siptag_refer_to = *_siptag_refer_to;
  *(struct tag_type_s *)siptag_refer_to_ref = *_siptag_refer_to_ref;
  *(struct tag_type_s *)siptag_authorization = *_siptag_authorization;
  *(struct tag_type_s *)siptag_authorization_ref = *_siptag_authorization_ref;
  *(struct tag_type_s *)siptag_organization = *_siptag_organization;
  *(struct tag_type_s *)siptag_organization_ref = *_siptag_organization_ref;
  *(struct tag_type_s *)siptag_request_disposition = *_siptag_request_disposition;
  *(struct tag_type_s *)siptag_request_disposition_ref = *_siptag_request_disposition_ref;
  *(struct tag_type_s *)siptag_content_disposition = *_siptag_content_disposition;
  *(struct tag_type_s *)siptag_content_disposition_ref = *_siptag_content_disposition_ref;
  *(struct tag_type_s *)siptag_proxy_authentication_info = *_siptag_proxy_authentication_info;
  *(struct tag_type_s *)siptag_proxy_authentication_info_ref = *_siptag_proxy_authentication_info_ref;
  *(struct tag_type_s *)siptag_etag = *_siptag_etag;
  *(struct tag_type_s *)siptag_etag_ref = *_siptag_etag_ref;

  return TRUE;
}

#endif
