#ifdef _WIN32
/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains magic required by Win32 DLLs to initialize
 * tag_typedef_t variables.
 * 
 * Do not, repeat, do not edit this file. Edit 'http_tag.c' instead.
 * 
 */

#define EXPORT __declspec(dllexport)

/*
 * This file is part of the Sofia-SIP package
 *
 * Copyright (C) 2005 Nokia Corporation.
 *
 * Contact: Pekka Pessi <pekka.pessi@nokia.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */

/**@internal @file http_tag.c  HTTP Tag classes
 *
 * This file is autogenerated from <http_tag.c.in>.
 *
 * This file is automatically generated from <http.h> by msg_parser.awk.
 *
 * @author Pekka Pessi <Pekka.Pessi@nokia.com>
 */

#include "config.h"

#undef TAG_NAMESPACE
#define TAG_NAMESPACE "http"

#define TAG_NAMESPACE "http"

#include <assert.h>
#include <stddef.h>
#include <string.h>

#include <sofia-sip/su.h>

#include <sofia-sip/http.h>
#include <sofia-sip/http_protos.h>
#include <sofia-sip/http_tag.h>
#include <sofia-sip/http_tag_class.h>

tag_typedef_t httptag_any;

EXPORT tag_typedef_t httptag_http_ref;
tag_typedef_t httptag_http;
EXPORT tag_typedef_t httptag_version_ref;
tag_typedef_t httptag_version;
EXPORT tag_typedef_t httptag_header_ref;
tag_typedef_t httptag_header =
	{{ TAG_NAMESPACE, "header", httphdrtag_class, 0 }};
EXPORT tag_typedef_t httptag_header_str_ref;
tag_typedef_t httptag_header_str;


EXPORT tag_typedef_t httptag_request_ref;
tag_typedef_t httptag_request;
EXPORT tag_typedef_t httptag_request_str_ref;
tag_typedef_t httptag_request_str;

EXPORT tag_typedef_t httptag_status_ref;
tag_typedef_t httptag_status;
EXPORT tag_typedef_t httptag_status_str_ref;
tag_typedef_t httptag_status_str;

EXPORT tag_typedef_t httptag_accept_ref;
tag_typedef_t httptag_accept;
EXPORT tag_typedef_t httptag_accept_str_ref;
tag_typedef_t httptag_accept_str;

EXPORT tag_typedef_t httptag_accept_charset_ref;
tag_typedef_t httptag_accept_charset;
EXPORT tag_typedef_t httptag_accept_charset_str_ref;
tag_typedef_t httptag_accept_charset_str;

EXPORT tag_typedef_t httptag_accept_encoding_ref;
tag_typedef_t httptag_accept_encoding;
EXPORT tag_typedef_t httptag_accept_encoding_str_ref;
tag_typedef_t httptag_accept_encoding_str;

EXPORT tag_typedef_t httptag_accept_language_ref;
tag_typedef_t httptag_accept_language;
EXPORT tag_typedef_t httptag_accept_language_str_ref;
tag_typedef_t httptag_accept_language_str;

EXPORT tag_typedef_t httptag_accept_ranges_ref;
tag_typedef_t httptag_accept_ranges;
EXPORT tag_typedef_t httptag_accept_ranges_str_ref;
tag_typedef_t httptag_accept_ranges_str;

EXPORT tag_typedef_t httptag_allow_ref;
tag_typedef_t httptag_allow;
EXPORT tag_typedef_t httptag_allow_str_ref;
tag_typedef_t httptag_allow_str;

EXPORT tag_typedef_t httptag_authentication_info_ref;
tag_typedef_t httptag_authentication_info;
EXPORT tag_typedef_t httptag_authentication_info_str_ref;
tag_typedef_t httptag_authentication_info_str;

EXPORT tag_typedef_t httptag_authorization_ref;
tag_typedef_t httptag_authorization;
EXPORT tag_typedef_t httptag_authorization_str_ref;
tag_typedef_t httptag_authorization_str;

EXPORT tag_typedef_t httptag_age_ref;
tag_typedef_t httptag_age;
EXPORT tag_typedef_t httptag_age_str_ref;
tag_typedef_t httptag_age_str;

EXPORT tag_typedef_t httptag_cache_control_ref;
tag_typedef_t httptag_cache_control;
EXPORT tag_typedef_t httptag_cache_control_str_ref;
tag_typedef_t httptag_cache_control_str;

EXPORT tag_typedef_t httptag_connection_ref;
tag_typedef_t httptag_connection;
EXPORT tag_typedef_t httptag_connection_str_ref;
tag_typedef_t httptag_connection_str;

EXPORT tag_typedef_t httptag_date_ref;
tag_typedef_t httptag_date;
EXPORT tag_typedef_t httptag_date_str_ref;
tag_typedef_t httptag_date_str;

EXPORT tag_typedef_t httptag_etag_ref;
tag_typedef_t httptag_etag;
EXPORT tag_typedef_t httptag_etag_str_ref;
tag_typedef_t httptag_etag_str;

EXPORT tag_typedef_t httptag_expect_ref;
tag_typedef_t httptag_expect;
EXPORT tag_typedef_t httptag_expect_str_ref;
tag_typedef_t httptag_expect_str;

EXPORT tag_typedef_t httptag_expires_ref;
tag_typedef_t httptag_expires;
EXPORT tag_typedef_t httptag_expires_str_ref;
tag_typedef_t httptag_expires_str;

EXPORT tag_typedef_t httptag_from_ref;
tag_typedef_t httptag_from;
EXPORT tag_typedef_t httptag_from_str_ref;
tag_typedef_t httptag_from_str;

EXPORT tag_typedef_t httptag_host_ref;
tag_typedef_t httptag_host;
EXPORT tag_typedef_t httptag_host_str_ref;
tag_typedef_t httptag_host_str;

EXPORT tag_typedef_t httptag_if_match_ref;
tag_typedef_t httptag_if_match;
EXPORT tag_typedef_t httptag_if_match_str_ref;
tag_typedef_t httptag_if_match_str;

EXPORT tag_typedef_t httptag_if_modified_since_ref;
tag_typedef_t httptag_if_modified_since;
EXPORT tag_typedef_t httptag_if_modified_since_str_ref;
tag_typedef_t httptag_if_modified_since_str;

EXPORT tag_typedef_t httptag_if_none_match_ref;
tag_typedef_t httptag_if_none_match;
EXPORT tag_typedef_t httptag_if_none_match_str_ref;
tag_typedef_t httptag_if_none_match_str;

EXPORT tag_typedef_t httptag_if_range_ref;
tag_typedef_t httptag_if_range;
EXPORT tag_typedef_t httptag_if_range_str_ref;
tag_typedef_t httptag_if_range_str;

EXPORT tag_typedef_t httptag_if_unmodified_since_ref;
tag_typedef_t httptag_if_unmodified_since;
EXPORT tag_typedef_t httptag_if_unmodified_since_str_ref;
tag_typedef_t httptag_if_unmodified_since_str;

EXPORT tag_typedef_t httptag_last_modified_ref;
tag_typedef_t httptag_last_modified;
EXPORT tag_typedef_t httptag_last_modified_str_ref;
tag_typedef_t httptag_last_modified_str;

EXPORT tag_typedef_t httptag_location_ref;
tag_typedef_t httptag_location;
EXPORT tag_typedef_t httptag_location_str_ref;
tag_typedef_t httptag_location_str;

EXPORT tag_typedef_t httptag_max_forwards_ref;
tag_typedef_t httptag_max_forwards;
EXPORT tag_typedef_t httptag_max_forwards_str_ref;
tag_typedef_t httptag_max_forwards_str;

EXPORT tag_typedef_t httptag_pragma_ref;
tag_typedef_t httptag_pragma;
EXPORT tag_typedef_t httptag_pragma_str_ref;
tag_typedef_t httptag_pragma_str;

EXPORT tag_typedef_t httptag_proxy_authenticate_ref;
tag_typedef_t httptag_proxy_authenticate;
EXPORT tag_typedef_t httptag_proxy_authenticate_str_ref;
tag_typedef_t httptag_proxy_authenticate_str;

EXPORT tag_typedef_t httptag_proxy_authorization_ref;
tag_typedef_t httptag_proxy_authorization;
EXPORT tag_typedef_t httptag_proxy_authorization_str_ref;
tag_typedef_t httptag_proxy_authorization_str;

EXPORT tag_typedef_t httptag_range_ref;
tag_typedef_t httptag_range;
EXPORT tag_typedef_t httptag_range_str_ref;
tag_typedef_t httptag_range_str;

EXPORT tag_typedef_t httptag_referer_ref;
tag_typedef_t httptag_referer;
EXPORT tag_typedef_t httptag_referer_str_ref;
tag_typedef_t httptag_referer_str;

EXPORT tag_typedef_t httptag_retry_after_ref;
tag_typedef_t httptag_retry_after;
EXPORT tag_typedef_t httptag_retry_after_str_ref;
tag_typedef_t httptag_retry_after_str;

EXPORT tag_typedef_t httptag_server_ref;
tag_typedef_t httptag_server;
EXPORT tag_typedef_t httptag_server_str_ref;
tag_typedef_t httptag_server_str;

EXPORT tag_typedef_t httptag_te_ref;
tag_typedef_t httptag_te;
EXPORT tag_typedef_t httptag_te_str_ref;
tag_typedef_t httptag_te_str;

EXPORT tag_typedef_t httptag_trailer_ref;
tag_typedef_t httptag_trailer;
EXPORT tag_typedef_t httptag_trailer_str_ref;
tag_typedef_t httptag_trailer_str;

EXPORT tag_typedef_t httptag_transfer_encoding_ref;
tag_typedef_t httptag_transfer_encoding;
EXPORT tag_typedef_t httptag_transfer_encoding_str_ref;
tag_typedef_t httptag_transfer_encoding_str;

EXPORT tag_typedef_t httptag_upgrade_ref;
tag_typedef_t httptag_upgrade;
EXPORT tag_typedef_t httptag_upgrade_str_ref;
tag_typedef_t httptag_upgrade_str;

EXPORT tag_typedef_t httptag_user_agent_ref;
tag_typedef_t httptag_user_agent;
EXPORT tag_typedef_t httptag_user_agent_str_ref;
tag_typedef_t httptag_user_agent_str;

EXPORT tag_typedef_t httptag_vary_ref;
tag_typedef_t httptag_vary;
EXPORT tag_typedef_t httptag_vary_str_ref;
tag_typedef_t httptag_vary_str;

EXPORT tag_typedef_t httptag_via_ref;
tag_typedef_t httptag_via;
EXPORT tag_typedef_t httptag_via_str_ref;
tag_typedef_t httptag_via_str;

EXPORT tag_typedef_t httptag_warning_ref;
tag_typedef_t httptag_warning;
EXPORT tag_typedef_t httptag_warning_str_ref;
tag_typedef_t httptag_warning_str;

EXPORT tag_typedef_t httptag_www_authenticate_ref;
tag_typedef_t httptag_www_authenticate;
EXPORT tag_typedef_t httptag_www_authenticate_str_ref;
tag_typedef_t httptag_www_authenticate_str;

EXPORT tag_typedef_t httptag_proxy_connection_ref;
tag_typedef_t httptag_proxy_connection;
EXPORT tag_typedef_t httptag_proxy_connection_str_ref;
tag_typedef_t httptag_proxy_connection_str;

EXPORT tag_typedef_t httptag_set_cookie_ref;
tag_typedef_t httptag_set_cookie;
EXPORT tag_typedef_t httptag_set_cookie_str_ref;
tag_typedef_t httptag_set_cookie_str;

EXPORT tag_typedef_t httptag_cookie_ref;
tag_typedef_t httptag_cookie;
EXPORT tag_typedef_t httptag_cookie_str_ref;
tag_typedef_t httptag_cookie_str;

EXPORT tag_typedef_t httptag_mime_version_ref;
tag_typedef_t httptag_mime_version;
EXPORT tag_typedef_t httptag_mime_version_str_ref;
tag_typedef_t httptag_mime_version_str;

EXPORT tag_typedef_t httptag_content_encoding_ref;
tag_typedef_t httptag_content_encoding;
EXPORT tag_typedef_t httptag_content_encoding_str_ref;
tag_typedef_t httptag_content_encoding_str;

EXPORT tag_typedef_t httptag_content_language_ref;
tag_typedef_t httptag_content_language;
EXPORT tag_typedef_t httptag_content_language_str_ref;
tag_typedef_t httptag_content_language_str;

EXPORT tag_typedef_t httptag_content_length_ref;
tag_typedef_t httptag_content_length;
EXPORT tag_typedef_t httptag_content_length_str_ref;
tag_typedef_t httptag_content_length_str;

EXPORT tag_typedef_t httptag_content_location_ref;
tag_typedef_t httptag_content_location;
EXPORT tag_typedef_t httptag_content_location_str_ref;
tag_typedef_t httptag_content_location_str;

EXPORT tag_typedef_t httptag_content_md5_ref;
tag_typedef_t httptag_content_md5;
EXPORT tag_typedef_t httptag_content_md5_str_ref;
tag_typedef_t httptag_content_md5_str;

EXPORT tag_typedef_t httptag_content_range_ref;
tag_typedef_t httptag_content_range;
EXPORT tag_typedef_t httptag_content_range_str_ref;
tag_typedef_t httptag_content_range_str;

EXPORT tag_typedef_t httptag_content_type_ref;
tag_typedef_t httptag_content_type;
EXPORT tag_typedef_t httptag_content_type_str_ref;
tag_typedef_t httptag_content_type_str;

EXPORT tag_typedef_t httptag_unknown_ref;
tag_typedef_t httptag_unknown;
EXPORT tag_typedef_t httptag_unknown_str_ref;
tag_typedef_t httptag_unknown_str;

EXPORT tag_typedef_t httptag_error_ref;
tag_typedef_t httptag_error;
EXPORT tag_typedef_t httptag_error_str_ref;
tag_typedef_t httptag_error_str;

EXPORT tag_typedef_t httptag_separator_ref;
tag_typedef_t httptag_separator;
EXPORT tag_typedef_t httptag_separator_str_ref;
tag_typedef_t httptag_separator_str;

EXPORT tag_typedef_t httptag_payload_ref;
tag_typedef_t httptag_payload;
EXPORT tag_typedef_t httptag_payload_str_ref;
tag_typedef_t httptag_payload_str;


#include <windows.h>

BOOL WINAPI DllMain(HINSTANCE hInst, DWORD fwdReason, LPVOID fImpLoad)
{
  tag_typedef_t _httptag_if_unmodified_since_str = HTTPSTRTAG_TYPEDEF(if_unmodified_since);
  tag_typedef_t _httptag_if_unmodified_since_str_ref =
    REFTAG_TYPEDEF(httptag_if_unmodified_since_str);
  tag_typedef_t _httptag_proxy_authenticate_str = HTTPSTRTAG_TYPEDEF(proxy_authenticate);
  tag_typedef_t _httptag_proxy_authenticate_str_ref =
    REFTAG_TYPEDEF(httptag_proxy_authenticate_str);
  tag_typedef_t _httptag_server = HTTPHDRTAG_TYPEDEF(server);
  tag_typedef_t _httptag_server_ref =
    REFTAG_TYPEDEF(httptag_server);
  tag_typedef_t _httptag_if_modified_since_str = HTTPSTRTAG_TYPEDEF(if_modified_since);
  tag_typedef_t _httptag_if_modified_since_str_ref =
    REFTAG_TYPEDEF(httptag_if_modified_since_str);
  tag_typedef_t _httptag_age = HTTPHDRTAG_TYPEDEF(age);
  tag_typedef_t _httptag_age_ref =
    REFTAG_TYPEDEF(httptag_age);
  tag_typedef_t _httptag_content_language_str = HTTPSTRTAG_TYPEDEF(content_language);
  tag_typedef_t _httptag_content_language_str_ref =
    REFTAG_TYPEDEF(httptag_content_language_str);
  tag_typedef_t _httptag_www_authenticate_str = HTTPSTRTAG_TYPEDEF(www_authenticate);
  tag_typedef_t _httptag_www_authenticate_str_ref =
    REFTAG_TYPEDEF(httptag_www_authenticate_str);
  tag_typedef_t _httptag_request = HTTPHDRTAG_TYPEDEF(request);
  tag_typedef_t _httptag_request_ref =
    REFTAG_TYPEDEF(httptag_request);
  tag_typedef_t _httptag_unknown = HTTPHDRTAG_TYPEDEF(unknown);
  tag_typedef_t _httptag_unknown_ref =
    REFTAG_TYPEDEF(httptag_unknown);
  tag_typedef_t _httptag_transfer_encoding_str = HTTPSTRTAG_TYPEDEF(transfer_encoding);
  tag_typedef_t _httptag_transfer_encoding_str_ref =
    REFTAG_TYPEDEF(httptag_transfer_encoding_str);
  tag_typedef_t _httptag_proxy_authenticate = HTTPHDRTAG_TYPEDEF(proxy_authenticate);
  tag_typedef_t _httptag_proxy_authenticate_ref =
    REFTAG_TYPEDEF(httptag_proxy_authenticate);
  tag_typedef_t _httptag_accept_language_str = HTTPSTRTAG_TYPEDEF(accept_language);
  tag_typedef_t _httptag_accept_language_str_ref =
    REFTAG_TYPEDEF(httptag_accept_language_str);
  tag_typedef_t _httptag_content_encoding_str = HTTPSTRTAG_TYPEDEF(content_encoding);
  tag_typedef_t _httptag_content_encoding_str_ref =
    REFTAG_TYPEDEF(httptag_content_encoding_str);
  tag_typedef_t _httptag_last_modified_str = HTTPSTRTAG_TYPEDEF(last_modified);
  tag_typedef_t _httptag_last_modified_str_ref =
    REFTAG_TYPEDEF(httptag_last_modified_str);
  tag_typedef_t _httptag_content_range_str = HTTPSTRTAG_TYPEDEF(content_range);
  tag_typedef_t _httptag_content_range_str_ref =
    REFTAG_TYPEDEF(httptag_content_range_str);
  tag_typedef_t _httptag_www_authenticate = HTTPHDRTAG_TYPEDEF(www_authenticate);
  tag_typedef_t _httptag_www_authenticate_ref =
    REFTAG_TYPEDEF(httptag_www_authenticate);
  tag_typedef_t _httptag_upgrade = HTTPHDRTAG_TYPEDEF(upgrade);
  tag_typedef_t _httptag_upgrade_ref =
    REFTAG_TYPEDEF(httptag_upgrade);
  tag_typedef_t _httptag_accept_encoding_str = HTTPSTRTAG_TYPEDEF(accept_encoding);
  tag_typedef_t _httptag_accept_encoding_str_ref =
    REFTAG_TYPEDEF(httptag_accept_encoding_str);
  tag_typedef_t _httptag_content_type_str = HTTPSTRTAG_TYPEDEF(content_type);
  tag_typedef_t _httptag_content_type_str_ref =
    REFTAG_TYPEDEF(httptag_content_type_str);
  tag_typedef_t _httptag_content_length_str = HTTPSTRTAG_TYPEDEF(content_length);
  tag_typedef_t _httptag_content_length_str_ref =
    REFTAG_TYPEDEF(httptag_content_length_str);
  tag_typedef_t _httptag_content_length = HTTPHDRTAG_TYPEDEF(content_length);
  tag_typedef_t _httptag_content_length_ref =
    REFTAG_TYPEDEF(httptag_content_length);
  tag_typedef_t _httptag_trailer = HTTPHDRTAG_TYPEDEF(trailer);
  tag_typedef_t _httptag_trailer_ref =
    REFTAG_TYPEDEF(httptag_trailer);
  tag_typedef_t _httptag_set_cookie_str = HTTPSTRTAG_TYPEDEF(set_cookie);
  tag_typedef_t _httptag_set_cookie_str_ref =
    REFTAG_TYPEDEF(httptag_set_cookie_str);
  tag_typedef_t _httptag_proxy_authorization_str = HTTPSTRTAG_TYPEDEF(proxy_authorization);
  tag_typedef_t _httptag_proxy_authorization_str_ref =
    REFTAG_TYPEDEF(httptag_proxy_authorization_str);
  tag_typedef_t _httptag_pragma_str = HTTPSTRTAG_TYPEDEF(pragma);
  tag_typedef_t _httptag_pragma_str_ref =
    REFTAG_TYPEDEF(httptag_pragma_str);
  tag_typedef_t _httptag_if_none_match_str = HTTPSTRTAG_TYPEDEF(if_none_match);
  tag_typedef_t _httptag_if_none_match_str_ref =
    REFTAG_TYPEDEF(httptag_if_none_match_str);
  tag_typedef_t _httptag_accept_ranges = HTTPHDRTAG_TYPEDEF(accept_ranges);
  tag_typedef_t _httptag_accept_ranges_ref =
    REFTAG_TYPEDEF(httptag_accept_ranges);
  tag_typedef_t _httptag_authentication_info_str = HTTPSTRTAG_TYPEDEF(authentication_info);
  tag_typedef_t _httptag_authentication_info_str_ref =
    REFTAG_TYPEDEF(httptag_authentication_info_str);
  tag_typedef_t _httptag_payload_str = HTTPSTRTAG_TYPEDEF(payload);
  tag_typedef_t _httptag_payload_str_ref =
    REFTAG_TYPEDEF(httptag_payload_str);
  tag_typedef_t _httptag_if_range_str = HTTPSTRTAG_TYPEDEF(if_range);
  tag_typedef_t _httptag_if_range_str_ref =
    REFTAG_TYPEDEF(httptag_if_range_str);
  tag_typedef_t _httptag_status = HTTPHDRTAG_TYPEDEF(status);
  tag_typedef_t _httptag_status_ref =
    REFTAG_TYPEDEF(httptag_status);
  tag_typedef_t _httptag_content_location_str = HTTPSTRTAG_TYPEDEF(content_location);
  tag_typedef_t _httptag_content_location_str_ref =
    REFTAG_TYPEDEF(httptag_content_location_str);
  tag_typedef_t _httptag_proxy_connection_str = HTTPSTRTAG_TYPEDEF(proxy_connection);
  tag_typedef_t _httptag_proxy_connection_str_ref =
    REFTAG_TYPEDEF(httptag_proxy_connection_str);
  tag_typedef_t _httptag_via_str = HTTPSTRTAG_TYPEDEF(via);
  tag_typedef_t _httptag_via_str_ref =
    REFTAG_TYPEDEF(httptag_via_str);
  tag_typedef_t _httptag_upgrade_str = HTTPSTRTAG_TYPEDEF(upgrade);
  tag_typedef_t _httptag_upgrade_str_ref =
    REFTAG_TYPEDEF(httptag_upgrade_str);
  tag_typedef_t _httptag_separator = HTTPHDRTAG_TYPEDEF(separator);
  tag_typedef_t _httptag_separator_ref =
    REFTAG_TYPEDEF(httptag_separator);
  tag_typedef_t _httptag_cookie_str = HTTPSTRTAG_TYPEDEF(cookie);
  tag_typedef_t _httptag_cookie_str_ref =
    REFTAG_TYPEDEF(httptag_cookie_str);
  tag_typedef_t _httptag_cache_control_str = HTTPSTRTAG_TYPEDEF(cache_control);
  tag_typedef_t _httptag_cache_control_str_ref =
    REFTAG_TYPEDEF(httptag_cache_control_str);
  tag_typedef_t _httptag_warning_str = HTTPSTRTAG_TYPEDEF(warning);
  tag_typedef_t _httptag_warning_str_ref =
    REFTAG_TYPEDEF(httptag_warning_str);
  tag_typedef_t _httptag_transfer_encoding = HTTPHDRTAG_TYPEDEF(transfer_encoding);
  tag_typedef_t _httptag_transfer_encoding_ref =
    REFTAG_TYPEDEF(httptag_transfer_encoding);
  tag_typedef_t _httptag_range_str = HTTPSTRTAG_TYPEDEF(range);
  tag_typedef_t _httptag_range_str_ref =
    REFTAG_TYPEDEF(httptag_range_str);
  tag_typedef_t _httptag_if_match_str = HTTPSTRTAG_TYPEDEF(if_match);
  tag_typedef_t _httptag_if_match_str_ref =
    REFTAG_TYPEDEF(httptag_if_match_str);
  tag_typedef_t _httptag_content_language = HTTPHDRTAG_TYPEDEF(content_language);
  tag_typedef_t _httptag_content_language_ref =
    REFTAG_TYPEDEF(httptag_content_language);
  tag_typedef_t _httptag_content_encoding = HTTPHDRTAG_TYPEDEF(content_encoding);
  tag_typedef_t _httptag_content_encoding_ref =
    REFTAG_TYPEDEF(httptag_content_encoding);
  tag_typedef_t _httptag_via = HTTPHDRTAG_TYPEDEF(via);
  tag_typedef_t _httptag_via_ref =
    REFTAG_TYPEDEF(httptag_via);
  tag_typedef_t _httptag_host = HTTPHDRTAG_TYPEDEF(host);
  tag_typedef_t _httptag_host_ref =
    REFTAG_TYPEDEF(httptag_host);
  tag_typedef_t _httptag_date_str = HTTPSTRTAG_TYPEDEF(date);
  tag_typedef_t _httptag_date_str_ref =
    REFTAG_TYPEDEF(httptag_date_str);
  tag_typedef_t _httptag_date = HTTPHDRTAG_TYPEDEF(date);
  tag_typedef_t _httptag_date_ref =
    REFTAG_TYPEDEF(httptag_date);
  tag_typedef_t _httptag_authorization_str = HTTPSTRTAG_TYPEDEF(authorization);
  tag_typedef_t _httptag_authorization_str_ref =
    REFTAG_TYPEDEF(httptag_authorization_str);
  tag_typedef_t _httptag_mime_version_str = HTTPSTRTAG_TYPEDEF(mime_version);
  tag_typedef_t _httptag_mime_version_str_ref =
    REFTAG_TYPEDEF(httptag_mime_version_str);
  tag_typedef_t _httptag_pragma = HTTPHDRTAG_TYPEDEF(pragma);
  tag_typedef_t _httptag_pragma_ref =
    REFTAG_TYPEDEF(httptag_pragma);
  tag_typedef_t _httptag_expires = HTTPHDRTAG_TYPEDEF(expires);
  tag_typedef_t _httptag_expires_ref =
    REFTAG_TYPEDEF(httptag_expires);
  tag_typedef_t _httptag_age_str = HTTPSTRTAG_TYPEDEF(age);
  tag_typedef_t _httptag_age_str_ref =
    REFTAG_TYPEDEF(httptag_age_str);
  tag_typedef_t _httptag_allow = HTTPHDRTAG_TYPEDEF(allow);
  tag_typedef_t _httptag_allow_ref =
    REFTAG_TYPEDEF(httptag_allow);
  tag_typedef_t _httptag_accept_language = HTTPHDRTAG_TYPEDEF(accept_language);
  tag_typedef_t _httptag_accept_language_ref =
    REFTAG_TYPEDEF(httptag_accept_language);
  tag_typedef_t _httptag_accept_encoding = HTTPHDRTAG_TYPEDEF(accept_encoding);
  tag_typedef_t _httptag_accept_encoding_ref =
    REFTAG_TYPEDEF(httptag_accept_encoding);
  tag_typedef_t _httptag_te_str = HTTPSTRTAG_TYPEDEF(te);
  tag_typedef_t _httptag_te_str_ref =
    REFTAG_TYPEDEF(httptag_te_str);
  tag_typedef_t _httptag_etag_str = HTTPSTRTAG_TYPEDEF(etag);
  tag_typedef_t _httptag_etag_str_ref =
    REFTAG_TYPEDEF(httptag_etag_str);
  tag_typedef_t _httptag_connection_str = HTTPSTRTAG_TYPEDEF(connection);
  tag_typedef_t _httptag_connection_str_ref =
    REFTAG_TYPEDEF(httptag_connection_str);
  tag_typedef_t _httptag_cache_control = HTTPHDRTAG_TYPEDEF(cache_control);
  tag_typedef_t _httptag_cache_control_ref =
    REFTAG_TYPEDEF(httptag_cache_control);
  tag_typedef_t _httptag_user_agent = HTTPHDRTAG_TYPEDEF(user_agent);
  tag_typedef_t _httptag_user_agent_ref =
    REFTAG_TYPEDEF(httptag_user_agent);
  tag_typedef_t _httptag_location_str = HTTPSTRTAG_TYPEDEF(location);
  tag_typedef_t _httptag_location_str_ref =
    REFTAG_TYPEDEF(httptag_location_str);
  tag_typedef_t _httptag_accept_ranges_str = HTTPSTRTAG_TYPEDEF(accept_ranges);
  tag_typedef_t _httptag_accept_ranges_str_ref =
    REFTAG_TYPEDEF(httptag_accept_ranges_str);
  tag_typedef_t _httptag_accept_charset_str = HTTPSTRTAG_TYPEDEF(accept_charset);
  tag_typedef_t _httptag_accept_charset_str_ref =
    REFTAG_TYPEDEF(httptag_accept_charset_str);
  tag_typedef_t _httptag_unknown_str = HTTPSTRTAG_TYPEDEF(unknown);
  tag_typedef_t _httptag_unknown_str_ref =
    REFTAG_TYPEDEF(httptag_unknown_str);
  tag_typedef_t _httptag_retry_after_str = HTTPSTRTAG_TYPEDEF(retry_after);
  tag_typedef_t _httptag_retry_after_str_ref =
    REFTAG_TYPEDEF(httptag_retry_after_str);
  tag_typedef_t _httptag_max_forwards_str = HTTPSTRTAG_TYPEDEF(max_forwards);
  tag_typedef_t _httptag_max_forwards_str_ref =
    REFTAG_TYPEDEF(httptag_max_forwards_str);
  tag_typedef_t _httptag_separator_str = HTTPSTRTAG_TYPEDEF(separator);
  tag_typedef_t _httptag_separator_str_ref =
    REFTAG_TYPEDEF(httptag_separator_str);
  tag_typedef_t _httptag_from_str = HTTPSTRTAG_TYPEDEF(from);
  tag_typedef_t _httptag_from_str_ref =
    REFTAG_TYPEDEF(httptag_from_str);
  tag_typedef_t _httptag_accept_charset = HTTPHDRTAG_TYPEDEF(accept_charset);
  tag_typedef_t _httptag_accept_charset_ref =
    REFTAG_TYPEDEF(httptag_accept_charset);
  tag_typedef_t _httptag_content_md5_str = HTTPSTRTAG_TYPEDEF(content_md5);
  tag_typedef_t _httptag_content_md5_str_ref =
    REFTAG_TYPEDEF(httptag_content_md5_str);
  tag_typedef_t _httptag_user_agent_str = HTTPSTRTAG_TYPEDEF(user_agent);
  tag_typedef_t _httptag_user_agent_str_ref =
    REFTAG_TYPEDEF(httptag_user_agent_str);
  tag_typedef_t _httptag_trailer_str = HTTPSTRTAG_TYPEDEF(trailer);
  tag_typedef_t _httptag_trailer_str_ref =
    REFTAG_TYPEDEF(httptag_trailer_str);
  tag_typedef_t _httptag_referer_str = HTTPSTRTAG_TYPEDEF(referer);
  tag_typedef_t _httptag_referer_str_ref =
    REFTAG_TYPEDEF(httptag_referer_str);
  tag_typedef_t _httptag_server_str = HTTPSTRTAG_TYPEDEF(server);
  tag_typedef_t _httptag_server_str_ref =
    REFTAG_TYPEDEF(httptag_server_str);
  tag_typedef_t _httptag_if_none_match = HTTPHDRTAG_TYPEDEF(if_none_match);
  tag_typedef_t _httptag_if_none_match_ref =
    REFTAG_TYPEDEF(httptag_if_none_match);
  tag_typedef_t _httptag_expires_str = HTTPSTRTAG_TYPEDEF(expires);
  tag_typedef_t _httptag_expires_str_ref =
    REFTAG_TYPEDEF(httptag_expires_str);
  tag_typedef_t _httptag_header_str = STRTAG_TYPEDEF(header_str);
  tag_typedef_t _httptag_header_str_ref =
    REFTAG_TYPEDEF(httptag_header_str);
  tag_typedef_t _httptag_error_str = HTTPSTRTAG_TYPEDEF(error);
  tag_typedef_t _httptag_error_str_ref =
    REFTAG_TYPEDEF(httptag_error_str);
  tag_typedef_t _httptag_max_forwards = HTTPHDRTAG_TYPEDEF(max_forwards);
  tag_typedef_t _httptag_max_forwards_ref =
    REFTAG_TYPEDEF(httptag_max_forwards);
  tag_typedef_t _httptag_if_unmodified_since = HTTPHDRTAG_TYPEDEF(if_unmodified_since);
  tag_typedef_t _httptag_if_unmodified_since_ref =
    REFTAG_TYPEDEF(httptag_if_unmodified_since);
  tag_typedef_t _httptag_status_str = HTTPSTRTAG_TYPEDEF(status);
  tag_typedef_t _httptag_status_str_ref =
    REFTAG_TYPEDEF(httptag_status_str);
  tag_typedef_t _httptag_request_str = HTTPSTRTAG_TYPEDEF(request);
  tag_typedef_t _httptag_request_str_ref =
    REFTAG_TYPEDEF(httptag_request_str);
  tag_typedef_t _httptag_expect_str = HTTPSTRTAG_TYPEDEF(expect);
  tag_typedef_t _httptag_expect_str_ref =
    REFTAG_TYPEDEF(httptag_expect_str);
  tag_typedef_t _httptag_accept_str = HTTPSTRTAG_TYPEDEF(accept);
  tag_typedef_t _httptag_accept_str_ref =
    REFTAG_TYPEDEF(httptag_accept_str);
  tag_typedef_t _httptag_if_modified_since = HTTPHDRTAG_TYPEDEF(if_modified_since);
  tag_typedef_t _httptag_if_modified_since_ref =
    REFTAG_TYPEDEF(httptag_if_modified_since);
  tag_typedef_t _httptag_header =
  tag_typedef_t _httptag_header_ref =
    REFTAG_TYPEDEF(httptag_header);
  tag_typedef_t _httptag_host_str = HTTPSTRTAG_TYPEDEF(host);
  tag_typedef_t _httptag_host_str_ref =
    REFTAG_TYPEDEF(httptag_host_str);
  tag_typedef_t _httptag_if_match = HTTPHDRTAG_TYPEDEF(if_match);
  tag_typedef_t _httptag_if_match_ref =
    REFTAG_TYPEDEF(httptag_if_match);
  tag_typedef_t _httptag_allow_str = HTTPSTRTAG_TYPEDEF(allow);
  tag_typedef_t _httptag_allow_str_ref =
    REFTAG_TYPEDEF(httptag_allow_str);
  tag_typedef_t _httptag_warning = HTTPHDRTAG_TYPEDEF(warning);
  tag_typedef_t _httptag_warning_ref =
    REFTAG_TYPEDEF(httptag_warning);
  tag_typedef_t _httptag_te = HTTPHDRTAG_TYPEDEF(te);
  tag_typedef_t _httptag_te_ref =
    REFTAG_TYPEDEF(httptag_te);
  tag_typedef_t _httptag_content_type = HTTPHDRTAG_TYPEDEF(content_type);
  tag_typedef_t _httptag_content_type_ref =
    REFTAG_TYPEDEF(httptag_content_type);
  tag_typedef_t _httptag_vary_str = HTTPSTRTAG_TYPEDEF(vary);
  tag_typedef_t _httptag_vary_str_ref =
    REFTAG_TYPEDEF(httptag_vary_str);
  tag_typedef_t _httptag_payload = HTTPHDRTAG_TYPEDEF(payload);
  tag_typedef_t _httptag_payload_ref =
    REFTAG_TYPEDEF(httptag_payload);
  tag_typedef_t _httptag_content_range = HTTPHDRTAG_TYPEDEF(content_range);
  tag_typedef_t _httptag_content_range_ref =
    REFTAG_TYPEDEF(httptag_content_range);
  tag_typedef_t _httptag_proxy_authorization = HTTPHDRTAG_TYPEDEF(proxy_authorization);
  tag_typedef_t _httptag_proxy_authorization_ref =
    REFTAG_TYPEDEF(httptag_proxy_authorization);
  tag_typedef_t _httptag_last_modified = HTTPHDRTAG_TYPEDEF(last_modified);
  tag_typedef_t _httptag_last_modified_ref =
    REFTAG_TYPEDEF(httptag_last_modified);
  tag_typedef_t _httptag_set_cookie = HTTPHDRTAG_TYPEDEF(set_cookie);
  tag_typedef_t _httptag_set_cookie_ref =
    REFTAG_TYPEDEF(httptag_set_cookie);
  tag_typedef_t _httptag_retry_after = HTTPHDRTAG_TYPEDEF(retry_after);
  tag_typedef_t _httptag_retry_after_ref =
    REFTAG_TYPEDEF(httptag_retry_after);
  tag_typedef_t _httptag_any = NSTAG_TYPEDEF(*);
  tag_typedef_t _httptag_any_ref =
    REFTAG_TYPEDEF(httptag_any);
  tag_typedef_t _httptag_content_location = HTTPHDRTAG_TYPEDEF(content_location);
  tag_typedef_t _httptag_content_location_ref =
    REFTAG_TYPEDEF(httptag_content_location);
  tag_typedef_t _httptag_if_range = HTTPHDRTAG_TYPEDEF(if_range);
  tag_typedef_t _httptag_if_range_ref =
    REFTAG_TYPEDEF(httptag_if_range);
  tag_typedef_t _httptag_from = HTTPHDRTAG_TYPEDEF(from);
  tag_typedef_t _httptag_from_ref =
    REFTAG_TYPEDEF(httptag_from);
  tag_typedef_t _httptag_cookie = HTTPHDRTAG_TYPEDEF(cookie);
  tag_typedef_t _httptag_cookie_ref =
    REFTAG_TYPEDEF(httptag_cookie);
  tag_typedef_t _httptag_proxy_connection = HTTPHDRTAG_TYPEDEF(proxy_connection);
  tag_typedef_t _httptag_proxy_connection_ref =
    REFTAG_TYPEDEF(httptag_proxy_connection);
  tag_typedef_t _httptag_referer = HTTPHDRTAG_TYPEDEF(referer);
  tag_typedef_t _httptag_referer_ref =
    REFTAG_TYPEDEF(httptag_referer);
  tag_typedef_t _httptag_range = HTTPHDRTAG_TYPEDEF(range);
  tag_typedef_t _httptag_range_ref =
    REFTAG_TYPEDEF(httptag_range);
  tag_typedef_t _httptag_authorization = HTTPHDRTAG_TYPEDEF(authorization);
  tag_typedef_t _httptag_authorization_ref =
    REFTAG_TYPEDEF(httptag_authorization);
  tag_typedef_t _httptag_http = HTTPMSGTAG_TYPEDEF(http);
  tag_typedef_t _httptag_http_ref =
    REFTAG_TYPEDEF(httptag_http);
  tag_typedef_t _httptag_content_md5 = HTTPHDRTAG_TYPEDEF(content_md5);
  tag_typedef_t _httptag_content_md5_ref =
    REFTAG_TYPEDEF(httptag_content_md5);
  tag_typedef_t _httptag_location = HTTPHDRTAG_TYPEDEF(location);
  tag_typedef_t _httptag_location_ref =
    REFTAG_TYPEDEF(httptag_location);
  tag_typedef_t _httptag_connection = HTTPHDRTAG_TYPEDEF(connection);
  tag_typedef_t _httptag_connection_ref =
    REFTAG_TYPEDEF(httptag_connection);
  tag_typedef_t _httptag_etag = HTTPHDRTAG_TYPEDEF(etag);
  tag_typedef_t _httptag_etag_ref =
    REFTAG_TYPEDEF(httptag_etag);
  tag_typedef_t _httptag_mime_version = HTTPHDRTAG_TYPEDEF(mime_version);
  tag_typedef_t _httptag_mime_version_ref =
    REFTAG_TYPEDEF(httptag_mime_version);
  tag_typedef_t _httptag_expect = HTTPHDRTAG_TYPEDEF(expect);
  tag_typedef_t _httptag_expect_ref =
    REFTAG_TYPEDEF(httptag_expect);
  tag_typedef_t _httptag_authentication_info = HTTPHDRTAG_TYPEDEF(authentication_info);
  tag_typedef_t _httptag_authentication_info_ref =
    REFTAG_TYPEDEF(httptag_authentication_info);
  tag_typedef_t _httptag_vary = HTTPHDRTAG_TYPEDEF(vary);
  tag_typedef_t _httptag_vary_ref =
    REFTAG_TYPEDEF(httptag_vary);
  tag_typedef_t _httptag_accept = HTTPHDRTAG_TYPEDEF(accept);
  tag_typedef_t _httptag_accept_ref =
    REFTAG_TYPEDEF(httptag_accept);
  tag_typedef_t _httptag_version = STRTAG_TYPEDEF(version);
  tag_typedef_t _httptag_version_ref =
    REFTAG_TYPEDEF(httptag_version);
  tag_typedef_t _httptag_error = HTTPHDRTAG_TYPEDEF(error);
  tag_typedef_t _httptag_error_ref =
    REFTAG_TYPEDEF(httptag_error);

  *(struct tag_type_s *)httptag_if_unmodified_since_str = *_httptag_if_unmodified_since_str;
  *(struct tag_type_s *)httptag_if_unmodified_since_str_ref = *_httptag_if_unmodified_since_str_ref;
  *(struct tag_type_s *)httptag_proxy_authenticate_str = *_httptag_proxy_authenticate_str;
  *(struct tag_type_s *)httptag_proxy_authenticate_str_ref = *_httptag_proxy_authenticate_str_ref;
  *(struct tag_type_s *)httptag_age = *_httptag_age;
  *(struct tag_type_s *)httptag_age_ref = *_httptag_age_ref;
  *(struct tag_type_s *)httptag_if_modified_since_str = *_httptag_if_modified_since_str;
  *(struct tag_type_s *)httptag_if_modified_since_str_ref = *_httptag_if_modified_since_str_ref;
  *(struct tag_type_s *)httptag_server = *_httptag_server;
  *(struct tag_type_s *)httptag_server_ref = *_httptag_server_ref;
  *(struct tag_type_s *)httptag_request = *_httptag_request;
  *(struct tag_type_s *)httptag_request_ref = *_httptag_request_ref;
  *(struct tag_type_s *)httptag_www_authenticate_str = *_httptag_www_authenticate_str;
  *(struct tag_type_s *)httptag_www_authenticate_str_ref = *_httptag_www_authenticate_str_ref;
  *(struct tag_type_s *)httptag_content_language_str = *_httptag_content_language_str;
  *(struct tag_type_s *)httptag_content_language_str_ref = *_httptag_content_language_str_ref;
  *(struct tag_type_s *)httptag_accept_language_str = *_httptag_accept_language_str;
  *(struct tag_type_s *)httptag_accept_language_str_ref = *_httptag_accept_language_str_ref;
  *(struct tag_type_s *)httptag_proxy_authenticate = *_httptag_proxy_authenticate;
  *(struct tag_type_s *)httptag_proxy_authenticate_ref = *_httptag_proxy_authenticate_ref;
  *(struct tag_type_s *)httptag_transfer_encoding_str = *_httptag_transfer_encoding_str;
  *(struct tag_type_s *)httptag_transfer_encoding_str_ref = *_httptag_transfer_encoding_str_ref;
  *(struct tag_type_s *)httptag_unknown = *_httptag_unknown;
  *(struct tag_type_s *)httptag_unknown_ref = *_httptag_unknown_ref;
  *(struct tag_type_s *)httptag_last_modified_str = *_httptag_last_modified_str;
  *(struct tag_type_s *)httptag_last_modified_str_ref = *_httptag_last_modified_str_ref;
  *(struct tag_type_s *)httptag_content_encoding_str = *_httptag_content_encoding_str;
  *(struct tag_type_s *)httptag_content_encoding_str_ref = *_httptag_content_encoding_str_ref;
  *(struct tag_type_s *)httptag_accept_encoding_str = *_httptag_accept_encoding_str;
  *(struct tag_type_s *)httptag_accept_encoding_str_ref = *_httptag_accept_encoding_str_ref;
  *(struct tag_type_s *)httptag_upgrade = *_httptag_upgrade;
  *(struct tag_type_s *)httptag_upgrade_ref = *_httptag_upgrade_ref;
  *(struct tag_type_s *)httptag_www_authenticate = *_httptag_www_authenticate;
  *(struct tag_type_s *)httptag_www_authenticate_ref = *_httptag_www_authenticate_ref;
  *(struct tag_type_s *)httptag_content_range_str = *_httptag_content_range_str;
  *(struct tag_type_s *)httptag_content_range_str_ref = *_httptag_content_range_str_ref;
  *(struct tag_type_s *)httptag_content_type_str = *_httptag_content_type_str;
  *(struct tag_type_s *)httptag_content_type_str_ref = *_httptag_content_type_str_ref;
  *(struct tag_type_s *)httptag_trailer = *_httptag_trailer;
  *(struct tag_type_s *)httptag_trailer_ref = *_httptag_trailer_ref;
  *(struct tag_type_s *)httptag_content_length = *_httptag_content_length;
  *(struct tag_type_s *)httptag_content_length_ref = *_httptag_content_length_ref;
  *(struct tag_type_s *)httptag_content_length_str = *_httptag_content_length_str;
  *(struct tag_type_s *)httptag_content_length_str_ref = *_httptag_content_length_str_ref;
  *(struct tag_type_s *)httptag_accept_ranges = *_httptag_accept_ranges;
  *(struct tag_type_s *)httptag_accept_ranges_ref = *_httptag_accept_ranges_ref;
  *(struct tag_type_s *)httptag_if_none_match_str = *_httptag_if_none_match_str;
  *(struct tag_type_s *)httptag_if_none_match_str_ref = *_httptag_if_none_match_str_ref;
  *(struct tag_type_s *)httptag_pragma_str = *_httptag_pragma_str;
  *(struct tag_type_s *)httptag_pragma_str_ref = *_httptag_pragma_str_ref;
  *(struct tag_type_s *)httptag_proxy_authorization_str = *_httptag_proxy_authorization_str;
  *(struct tag_type_s *)httptag_proxy_authorization_str_ref = *_httptag_proxy_authorization_str_ref;
  *(struct tag_type_s *)httptag_set_cookie_str = *_httptag_set_cookie_str;
  *(struct tag_type_s *)httptag_set_cookie_str_ref = *_httptag_set_cookie_str_ref;
  *(struct tag_type_s *)httptag_authentication_info_str = *_httptag_authentication_info_str;
  *(struct tag_type_s *)httptag_authentication_info_str_ref = *_httptag_authentication_info_str_ref;
  *(struct tag_type_s *)httptag_status = *_httptag_status;
  *(struct tag_type_s *)httptag_status_ref = *_httptag_status_ref;
  *(struct tag_type_s *)httptag_if_range_str = *_httptag_if_range_str;
  *(struct tag_type_s *)httptag_if_range_str_ref = *_httptag_if_range_str_ref;
  *(struct tag_type_s *)httptag_payload_str = *_httptag_payload_str;
  *(struct tag_type_s *)httptag_payload_str_ref = *_httptag_payload_str_ref;
  *(struct tag_type_s *)httptag_upgrade_str = *_httptag_upgrade_str;
  *(struct tag_type_s *)httptag_upgrade_str_ref = *_httptag_upgrade_str_ref;
  *(struct tag_type_s *)httptag_via_str = *_httptag_via_str;
  *(struct tag_type_s *)httptag_via_str_ref = *_httptag_via_str_ref;
  *(struct tag_type_s *)httptag_proxy_connection_str = *_httptag_proxy_connection_str;
  *(struct tag_type_s *)httptag_proxy_connection_str_ref = *_httptag_proxy_connection_str_ref;
  *(struct tag_type_s *)httptag_content_location_str = *_httptag_content_location_str;
  *(struct tag_type_s *)httptag_content_location_str_ref = *_httptag_content_location_str_ref;
  *(struct tag_type_s *)httptag_cache_control_str = *_httptag_cache_control_str;
  *(struct tag_type_s *)httptag_cache_control_str_ref = *_httptag_cache_control_str_ref;
  *(struct tag_type_s *)httptag_cookie_str = *_httptag_cookie_str;
  *(struct tag_type_s *)httptag_cookie_str_ref = *_httptag_cookie_str_ref;
  *(struct tag_type_s *)httptag_separator = *_httptag_separator;
  *(struct tag_type_s *)httptag_separator_ref = *_httptag_separator_ref;
  *(struct tag_type_s *)httptag_if_match_str = *_httptag_if_match_str;
  *(struct tag_type_s *)httptag_if_match_str_ref = *_httptag_if_match_str_ref;
  *(struct tag_type_s *)httptag_range_str = *_httptag_range_str;
  *(struct tag_type_s *)httptag_range_str_ref = *_httptag_range_str_ref;
  *(struct tag_type_s *)httptag_transfer_encoding = *_httptag_transfer_encoding;
  *(struct tag_type_s *)httptag_transfer_encoding_ref = *_httptag_transfer_encoding_ref;
  *(struct tag_type_s *)httptag_warning_str = *_httptag_warning_str;
  *(struct tag_type_s *)httptag_warning_str_ref = *_httptag_warning_str_ref;
  *(struct tag_type_s *)httptag_authorization_str = *_httptag_authorization_str;
  *(struct tag_type_s *)httptag_authorization_str_ref = *_httptag_authorization_str_ref;
  *(struct tag_type_s *)httptag_date = *_httptag_date;
  *(struct tag_type_s *)httptag_date_ref = *_httptag_date_ref;
  *(struct tag_type_s *)httptag_date_str = *_httptag_date_str;
  *(struct tag_type_s *)httptag_date_str_ref = *_httptag_date_str_ref;
  *(struct tag_type_s *)httptag_host = *_httptag_host;
  *(struct tag_type_s *)httptag_host_ref = *_httptag_host_ref;
  *(struct tag_type_s *)httptag_via = *_httptag_via;
  *(struct tag_type_s *)httptag_via_ref = *_httptag_via_ref;
  *(struct tag_type_s *)httptag_content_encoding = *_httptag_content_encoding;
  *(struct tag_type_s *)httptag_content_encoding_ref = *_httptag_content_encoding_ref;
  *(struct tag_type_s *)httptag_content_language = *_httptag_content_language;
  *(struct tag_type_s *)httptag_content_language_ref = *_httptag_content_language_ref;
  *(struct tag_type_s *)httptag_accept_encoding = *_httptag_accept_encoding;
  *(struct tag_type_s *)httptag_accept_encoding_ref = *_httptag_accept_encoding_ref;
  *(struct tag_type_s *)httptag_accept_language = *_httptag_accept_language;
  *(struct tag_type_s *)httptag_accept_language_ref = *_httptag_accept_language_ref;
  *(struct tag_type_s *)httptag_allow = *_httptag_allow;
  *(struct tag_type_s *)httptag_allow_ref = *_httptag_allow_ref;
  *(struct tag_type_s *)httptag_age_str = *_httptag_age_str;
  *(struct tag_type_s *)httptag_age_str_ref = *_httptag_age_str_ref;
  *(struct tag_type_s *)httptag_expires = *_httptag_expires;
  *(struct tag_type_s *)httptag_expires_ref = *_httptag_expires_ref;
  *(struct tag_type_s *)httptag_pragma = *_httptag_pragma;
  *(struct tag_type_s *)httptag_pragma_ref = *_httptag_pragma_ref;
  *(struct tag_type_s *)httptag_mime_version_str = *_httptag_mime_version_str;
  *(struct tag_type_s *)httptag_mime_version_str_ref = *_httptag_mime_version_str_ref;
  *(struct tag_type_s *)httptag_etag_str = *_httptag_etag_str;
  *(struct tag_type_s *)httptag_etag_str_ref = *_httptag_etag_str_ref;
  *(struct tag_type_s *)httptag_te_str = *_httptag_te_str;
  *(struct tag_type_s *)httptag_te_str_ref = *_httptag_te_str_ref;
  *(struct tag_type_s *)httptag_cache_control = *_httptag_cache_control;
  *(struct tag_type_s *)httptag_cache_control_ref = *_httptag_cache_control_ref;
  *(struct tag_type_s *)httptag_connection_str = *_httptag_connection_str;
  *(struct tag_type_s *)httptag_connection_str_ref = *_httptag_connection_str_ref;
  *(struct tag_type_s *)httptag_user_agent = *_httptag_user_agent;
  *(struct tag_type_s *)httptag_user_agent_ref = *_httptag_user_agent_ref;
  *(struct tag_type_s *)httptag_accept_charset_str = *_httptag_accept_charset_str;
  *(struct tag_type_s *)httptag_accept_charset_str_ref = *_httptag_accept_charset_str_ref;
  *(struct tag_type_s *)httptag_accept_ranges_str = *_httptag_accept_ranges_str;
  *(struct tag_type_s *)httptag_accept_ranges_str_ref = *_httptag_accept_ranges_str_ref;
  *(struct tag_type_s *)httptag_location_str = *_httptag_location_str;
  *(struct tag_type_s *)httptag_location_str_ref = *_httptag_location_str_ref;
  *(struct tag_type_s *)httptag_max_forwards_str = *_httptag_max_forwards_str;
  *(struct tag_type_s *)httptag_max_forwards_str_ref = *_httptag_max_forwards_str_ref;
  *(struct tag_type_s *)httptag_retry_after_str = *_httptag_retry_after_str;
  *(struct tag_type_s *)httptag_retry_after_str_ref = *_httptag_retry_after_str_ref;
  *(struct tag_type_s *)httptag_unknown_str = *_httptag_unknown_str;
  *(struct tag_type_s *)httptag_unknown_str_ref = *_httptag_unknown_str_ref;
  *(struct tag_type_s *)httptag_accept_charset = *_httptag_accept_charset;
  *(struct tag_type_s *)httptag_accept_charset_ref = *_httptag_accept_charset_ref;
  *(struct tag_type_s *)httptag_from_str = *_httptag_from_str;
  *(struct tag_type_s *)httptag_from_str_ref = *_httptag_from_str_ref;
  *(struct tag_type_s *)httptag_separator_str = *_httptag_separator_str;
  *(struct tag_type_s *)httptag_separator_str_ref = *_httptag_separator_str_ref;
  *(struct tag_type_s *)httptag_user_agent_str = *_httptag_user_agent_str;
  *(struct tag_type_s *)httptag_user_agent_str_ref = *_httptag_user_agent_str_ref;
  *(struct tag_type_s *)httptag_content_md5_str = *_httptag_content_md5_str;
  *(struct tag_type_s *)httptag_content_md5_str_ref = *_httptag_content_md5_str_ref;
  *(struct tag_type_s *)httptag_referer_str = *_httptag_referer_str;
  *(struct tag_type_s *)httptag_referer_str_ref = *_httptag_referer_str_ref;
  *(struct tag_type_s *)httptag_trailer_str = *_httptag_trailer_str;
  *(struct tag_type_s *)httptag_trailer_str_ref = *_httptag_trailer_str_ref;
  *(struct tag_type_s *)httptag_header_str = *_httptag_header_str;
  *(struct tag_type_s *)httptag_header_str_ref = *_httptag_header_str_ref;
  *(struct tag_type_s *)httptag_expires_str = *_httptag_expires_str;
  *(struct tag_type_s *)httptag_expires_str_ref = *_httptag_expires_str_ref;
  *(struct tag_type_s *)httptag_if_none_match = *_httptag_if_none_match;
  *(struct tag_type_s *)httptag_if_none_match_ref = *_httptag_if_none_match_ref;
  *(struct tag_type_s *)httptag_server_str = *_httptag_server_str;
  *(struct tag_type_s *)httptag_server_str_ref = *_httptag_server_str_ref;
  *(struct tag_type_s *)httptag_request_str = *_httptag_request_str;
  *(struct tag_type_s *)httptag_request_str_ref = *_httptag_request_str_ref;
  *(struct tag_type_s *)httptag_status_str = *_httptag_status_str;
  *(struct tag_type_s *)httptag_status_str_ref = *_httptag_status_str_ref;
  *(struct tag_type_s *)httptag_if_unmodified_since = *_httptag_if_unmodified_since;
  *(struct tag_type_s *)httptag_if_unmodified_since_ref = *_httptag_if_unmodified_since_ref;
  *(struct tag_type_s *)httptag_max_forwards = *_httptag_max_forwards;
  *(struct tag_type_s *)httptag_max_forwards_ref = *_httptag_max_forwards_ref;
  *(struct tag_type_s *)httptag_error_str = *_httptag_error_str;
  *(struct tag_type_s *)httptag_error_str_ref = *_httptag_error_str_ref;
  *(struct tag_type_s *)httptag_accept_str = *_httptag_accept_str;
  *(struct tag_type_s *)httptag_accept_str_ref = *_httptag_accept_str_ref;
  *(struct tag_type_s *)httptag_expect_str = *_httptag_expect_str;
  *(struct tag_type_s *)httptag_expect_str_ref = *_httptag_expect_str_ref;
  *(struct tag_type_s *)httptag_header = *_httptag_header;
  *(struct tag_type_s *)httptag_header_ref = *_httptag_header_ref;
  *(struct tag_type_s *)httptag_if_modified_since = *_httptag_if_modified_since;
  *(struct tag_type_s *)httptag_if_modified_since_ref = *_httptag_if_modified_since_ref;
  *(struct tag_type_s *)httptag_host_str = *_httptag_host_str;
  *(struct tag_type_s *)httptag_host_str_ref = *_httptag_host_str_ref;
  *(struct tag_type_s *)httptag_if_match = *_httptag_if_match;
  *(struct tag_type_s *)httptag_if_match_ref = *_httptag_if_match_ref;
  *(struct tag_type_s *)httptag_allow_str = *_httptag_allow_str;
  *(struct tag_type_s *)httptag_allow_str_ref = *_httptag_allow_str_ref;
  *(struct tag_type_s *)httptag_warning = *_httptag_warning;
  *(struct tag_type_s *)httptag_warning_ref = *_httptag_warning_ref;
  *(struct tag_type_s *)httptag_te = *_httptag_te;
  *(struct tag_type_s *)httptag_te_ref = *_httptag_te_ref;
  *(struct tag_type_s *)httptag_vary_str = *_httptag_vary_str;
  *(struct tag_type_s *)httptag_vary_str_ref = *_httptag_vary_str_ref;
  *(struct tag_type_s *)httptag_content_type = *_httptag_content_type;
  *(struct tag_type_s *)httptag_content_type_ref = *_httptag_content_type_ref;
  *(struct tag_type_s *)httptag_content_range = *_httptag_content_range;
  *(struct tag_type_s *)httptag_content_range_ref = *_httptag_content_range_ref;
  *(struct tag_type_s *)httptag_payload = *_httptag_payload;
  *(struct tag_type_s *)httptag_payload_ref = *_httptag_payload_ref;
  *(struct tag_type_s *)httptag_last_modified = *_httptag_last_modified;
  *(struct tag_type_s *)httptag_last_modified_ref = *_httptag_last_modified_ref;
  *(struct tag_type_s *)httptag_proxy_authorization = *_httptag_proxy_authorization;
  *(struct tag_type_s *)httptag_proxy_authorization_ref = *_httptag_proxy_authorization_ref;
  *(struct tag_type_s *)httptag_any = *_httptag_any;
  *(struct tag_type_s *)httptag_any_ref = *_httptag_any_ref;
  *(struct tag_type_s *)httptag_retry_after = *_httptag_retry_after;
  *(struct tag_type_s *)httptag_retry_after_ref = *_httptag_retry_after_ref;
  *(struct tag_type_s *)httptag_set_cookie = *_httptag_set_cookie;
  *(struct tag_type_s *)httptag_set_cookie_ref = *_httptag_set_cookie_ref;
  *(struct tag_type_s *)httptag_from = *_httptag_from;
  *(struct tag_type_s *)httptag_from_ref = *_httptag_from_ref;
  *(struct tag_type_s *)httptag_if_range = *_httptag_if_range;
  *(struct tag_type_s *)httptag_if_range_ref = *_httptag_if_range_ref;
  *(struct tag_type_s *)httptag_content_location = *_httptag_content_location;
  *(struct tag_type_s *)httptag_content_location_ref = *_httptag_content_location_ref;
  *(struct tag_type_s *)httptag_referer = *_httptag_referer;
  *(struct tag_type_s *)httptag_referer_ref = *_httptag_referer_ref;
  *(struct tag_type_s *)httptag_proxy_connection = *_httptag_proxy_connection;
  *(struct tag_type_s *)httptag_proxy_connection_ref = *_httptag_proxy_connection_ref;
  *(struct tag_type_s *)httptag_cookie = *_httptag_cookie;
  *(struct tag_type_s *)httptag_cookie_ref = *_httptag_cookie_ref;
  *(struct tag_type_s *)httptag_authorization = *_httptag_authorization;
  *(struct tag_type_s *)httptag_authorization_ref = *_httptag_authorization_ref;
  *(struct tag_type_s *)httptag_range = *_httptag_range;
  *(struct tag_type_s *)httptag_range_ref = *_httptag_range_ref;
  *(struct tag_type_s *)httptag_http = *_httptag_http;
  *(struct tag_type_s *)httptag_http_ref = *_httptag_http_ref;
  *(struct tag_type_s *)httptag_content_md5 = *_httptag_content_md5;
  *(struct tag_type_s *)httptag_content_md5_ref = *_httptag_content_md5_ref;
  *(struct tag_type_s *)httptag_connection = *_httptag_connection;
  *(struct tag_type_s *)httptag_connection_ref = *_httptag_connection_ref;
  *(struct tag_type_s *)httptag_location = *_httptag_location;
  *(struct tag_type_s *)httptag_location_ref = *_httptag_location_ref;
  *(struct tag_type_s *)httptag_etag = *_httptag_etag;
  *(struct tag_type_s *)httptag_etag_ref = *_httptag_etag_ref;
  *(struct tag_type_s *)httptag_mime_version = *_httptag_mime_version;
  *(struct tag_type_s *)httptag_mime_version_ref = *_httptag_mime_version_ref;
  *(struct tag_type_s *)httptag_expect = *_httptag_expect;
  *(struct tag_type_s *)httptag_expect_ref = *_httptag_expect_ref;
  *(struct tag_type_s *)httptag_authentication_info = *_httptag_authentication_info;
  *(struct tag_type_s *)httptag_authentication_info_ref = *_httptag_authentication_info_ref;
  *(struct tag_type_s *)httptag_accept = *_httptag_accept;
  *(struct tag_type_s *)httptag_accept_ref = *_httptag_accept_ref;
  *(struct tag_type_s *)httptag_vary = *_httptag_vary;
  *(struct tag_type_s *)httptag_vary_ref = *_httptag_vary_ref;
  *(struct tag_type_s *)httptag_version = *_httptag_version;
  *(struct tag_type_s *)httptag_version_ref = *_httptag_version_ref;
  *(struct tag_type_s *)httptag_error = *_httptag_error;
  *(struct tag_type_s *)httptag_error_ref = *_httptag_error_ref;

  return TRUE;
}

#endif
